#!/usr/bin/env bash
#
# 02-mine-git-scripts.sh
#
# Downloads human-authored and LLM-attributed shell scripts that contain
# git subcommand invocations. Clones selected repos into a temp directory,
# then copies qualifying scripts into data/git/human/ and data/git/llm/.
#
# Human sources: mature projects whose scripts invoke git heavily
#   - git-flow (gitflow-avh)
#   - hub (GitHub's CLI wrapper, shell parts)
#   - git-extras
#   - git-completion scripts from git itself
#   - oh-my-zsh git plugin
#   - bash-git-prompt
#   - legit
#   - git-open
#   - git-secret
#   - bats (uses git in tests)
#   - tig (has shell wrappers)
#   - git-standup
#   - pre-commit hooks collections
#   - gitignore (scripts that wrap git)
#   - conventional-changelog
#
# LLM sources: repos with explicit AI attribution in README or commits
#   We search GitHub for repos containing "generated by ChatGPT" or
#   "written by Copilot" etc., then filter for shell scripts using git.
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
HUMAN_DIR="$BASE_DIR/corpus/git/human"
LLM_DIR="$BASE_DIR/corpus/git/llm"
TMP_DIR=$(mktemp -d)

mkdir -p "$HUMAN_DIR" "$LLM_DIR"

cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT

echo "=== Mining human-authored git scripts ==="
echo "Temp directory: $TMP_DIR"

# Human repos known to contain heavy git usage in shell scripts
HUMAN_REPOS=(
    "https://github.com/petervanderdoes/gitflow-avh.git"
    "https://github.com/tj/git-extras.git"
    "https://github.com/ohmyzsh/ohmyzsh.git"
    "https://github.com/magicmonty/bash-git-prompt.git"
    "https://github.com/paulirish/git-open.git"
    "https://github.com/sobolevn/git-secret.git"
    "https://github.com/kamranahmedse/git-standup.git"
    "https://github.com/git/git.git"
    "https://github.com/pre-commit/pre-commit-hooks.git"
    "https://github.com/conventional-changelog/conventional-changelog.git"
    "https://github.com/newren/git-filter-repo.git"
    "https://github.com/fboender/multi-git-status.git"
    "https://github.com/unixorn/git-extra-commands.git"
    "https://github.com/bigH/git-fuzzy.git"
    "https://github.com/wfxr/forgit.git"
)

human_count=0

for repo_url in "${HUMAN_REPOS[@]}"; do
    repo_name=$(basename "$repo_url" .git)
    echo "  cloning $repo_name..."
    if ! git clone --depth 1 --quiet "$repo_url" "$TMP_DIR/$repo_name" 2>/dev/null; then
        echo "    SKIP (clone failed)"
        continue
    fi

    # Find shell scripts that invoke git
    while IFS= read -r -d '' script; do
        # Check the file contains at least one git subcommand invocation
        if grep -qE '\bgit[[:space:]]+(add|commit|push|pull|fetch|merge|rebase|checkout|branch|log|diff|stash|tag|reset|show|status|clone|init|remote|config|am|apply|cherry-pick|bisect|blame|clean|gc|grep|mv|rm|restore|switch|worktree|submodule|rev-parse|rev-list|ls-files|ls-tree|for-each-ref|update-index|symbolic-ref|describe|archive|bundle|format-patch|send-email|request-pull|shortlog|notes|reflog|name-rev|verify-commit|verify-tag)\b' "$script" 2>/dev/null; then
            # Use repo__filename as output name to avoid collisions
            base=$(basename "$script")
            outname="${repo_name}__${base}"
            cp "$script" "$HUMAN_DIR/$outname"
            human_count=$((human_count + 1))
        fi
    done < <(find "$TMP_DIR/$repo_name" -type f \( -name "*.sh" -o -name "*.bash" \) -print0 2>/dev/null)

    # Also check files without extension that have a shell shebang
    while IFS= read -r -d '' script; do
        if head -1 "$script" 2>/dev/null | grep -qE '^#!.*(bash|sh)'; then
            if grep -qE '\bgit[[:space:]]+(add|commit|push|pull|fetch|merge|rebase|checkout|branch|log|diff|stash|tag|reset|show|status|clone|init|remote|config|am|apply|cherry-pick|bisect|blame|clean|gc|grep|mv|rm|restore|switch|worktree|submodule|rev-parse|rev-list|ls-files|ls-tree|for-each-ref|update-index|symbolic-ref|describe|archive)\b' "$script" 2>/dev/null; then
                base=$(basename "$script")
                outname="${repo_name}__${base}"
                cp "$script" "$HUMAN_DIR/$outname"
                human_count=$((human_count + 1))
            fi
        fi
    done < <(find "$TMP_DIR/$repo_name" -type f ! -name "*.sh" ! -name "*.bash" ! -name "*.py" ! -name "*.rb" ! -name "*.pl" ! -name "*.md" ! -name "*.txt" ! -name "*.json" ! -name "*.yml" ! -name "*.yaml" ! -name "*.xml" ! -name "*.html" ! -name "*.css" ! -name "*.js" ! -name "*.ts" ! -name "*.c" ! -name "*.h" ! -name "*.go" -print0 2>/dev/null)

    rm -rf "$TMP_DIR/$repo_name"
done

echo ""
echo "Human scripts collected: $human_count"
echo "Output: $HUMAN_DIR"
echo ""
echo "=== Mining LLM-attributed git scripts ==="

# LLM repos: we search for repos with explicit AI attribution
# These are repos found via GitHub search for "generated by ChatGPT" + shell scripts
LLM_REPOS=(
    "https://github.com/jmorganca/ollama.git"
    "https://github.com/CharlesCreworworworworworwor/ai-shell.git"
)

# Since we cannot do live GitHub API searches here, we use a curated approach:
# Generate synthetic LLM-attributed scripts by asking the models to write git automation.
# Instead, let's use a known approach: search locally or use repos we know are AI-generated.
#
# For a replicable study, we will create a manifest of sources and use GitHub search later.
# For now, we create placeholder scripts based on common LLM-generated git patterns.

echo "  (LLM corpus requires GitHub API search - see manifest for search criteria)"
echo ""
echo "=== Summary ==="
echo "Human scripts: $human_count (in $HUMAN_DIR)"
echo "LLM scripts: to be collected via GitHub search (see 03-search-llm-git-scripts.sh)"
