#!/bin/bash
#
# ci-check-attribution.sh - CI check for AI attribution policy compliance
#
# This script checks all commits in a PR for AI attribution violations.
# Used in GitHub Actions CI pipeline.
#
# Exit codes:
#   0 - No violations found
#   1 - AI attribution detected (policy violation)
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 AI Attribution Policy Check"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# AI attribution patterns to detect
AI_PATTERNS=(
    "Co-Authored-By: GitHub Copilot"
    "Co-Authored-By: Cursor"
    "Co-Authored-By: Codeium"
    "Co-Authored-By: Tabnine"
    "Co-Authored-By: Windsurf"
    "Co-Authored-By: Amazon Q"
    "Co-Authored-By: Anthropic"
    "Co-Authored-By: OpenAI"
    "Generated with Claude"
    "Generated by Copilot"
    "🤖 Created with"
    "🤖 Made with"
)

# Determine commit range to check
if [ -n "$GITHUB_BASE_REF" ]; then
    # GitHub Actions PR context
    BASE_REF="origin/$GITHUB_BASE_REF"
    HEAD_REF="HEAD"
    echo "Checking PR commits: $BASE_REF..$HEAD_REF"
elif [ -n "$CI_COMMIT_RANGE" ]; then
    # Generic CI with commit range
    BASE_REF=$(echo "$CI_COMMIT_RANGE" | cut -d'.' -f1)
    HEAD_REF=$(echo "$CI_COMMIT_RANGE" | cut -d'.' -f4)
    echo "Checking commit range: $BASE_REF..$HEAD_REF"
else
    # Local check - last commit only
    BASE_REF="HEAD~1"
    HEAD_REF="HEAD"
    echo "Checking last commit: $HEAD_REF"
fi

echo ""

# Get commit messages in range
COMMITS=$(git log --format="%H|%s|%b" "$BASE_REF".."$HEAD_REF" 2>/dev/null || echo "")

if [ -z "$COMMITS" ]; then
    echo -e "${YELLOW}⚠️  No commits to check${NC}"
    exit 0
fi

# Check each commit
VIOLATION_FOUND=false
VIOLATION_DETAILS=""
COMMIT_COUNT=0

while IFS='|' read -r hash subject body; do
    COMMIT_COUNT=$((COMMIT_COUNT + 1))
    COMMIT_MSG="$subject $body"

    for pattern in "${AI_PATTERNS[@]}"; do
        if echo "$COMMIT_MSG" | grep -qi "$pattern"; then
            VIOLATION_FOUND=true
            VIOLATION_DETAILS="${VIOLATION_DETAILS}\n\n❌ Commit: ${hash:0:8}"
            VIOLATION_DETAILS="${VIOLATION_DETAILS}\n   Subject: $subject"
            VIOLATION_DETAILS="${VIOLATION_DETAILS}\n   Violation: $pattern"
        fi
    done
done <<< "$COMMITS"

echo "Checked $COMMIT_COUNT commit(s)"
echo ""

if [ "$VIOLATION_FOUND" = true ]; then
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${RED}❌ BUILD FAILED - AI Attribution Policy Violation${NC}"
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo -e "${YELLOW}Policy Violations Detected:${NC}"
    echo -e "${VIOLATION_DETAILS}"
    echo ""
    echo "Policy: AI tools are development assistants, not authors."
    echo ""
    echo "To fix:"
    echo "  1. Rewrite commit messages to remove AI attribution"
    echo "  2. Use: git rebase -i $BASE_REF"
    echo "  3. For each violating commit, use 'reword' to edit the message"
    echo "  4. Remove any 'Co-Authored-By: [AI]' or 'Generated with' lines"
    echo "  5. Force push: git push --force-with-lease"
    echo ""
    echo "Reference: AI_ATTRIBUTION_POLICY.md"
    echo ""
    exit 1
else
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}✅ AI Attribution Policy Check Passed${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "All commits comply with AI Attribution Policy."
    echo "No AI co-author lines or 'Generated with' statements found."
    echo ""
    exit 0
fi
