#!/bin/bash

# Script pentru descărcarea completă a aplicației React Notificări
# Generated by Copilot

echo "🚀 Pregătirea aplicației pentru descărcare..."

# Creează directorul de export
mkdir -p /tmp/react-notificari-export
cd /workspaces/codespaces-react

echo "📁 Copierea fișierelor..."

# Copiază toate fișierele importante
cp -r . /tmp/react-notificari-export/

# Intră în directorul de export
cd /tmp/react-notificari-export

echo "🧹 Curățarea fișierelor temporare..."

# Șterge fișierele temporare și node_modules
rm -rf node_modules
rm -rf backend/node_modules
rm -rf .git
rm -rf backend/logs
rm -rf backend/data/*.backup
rm -rf backend/data/*.bak.*

echo "📦 Crearea arhivei ZIP..."

# Creează arhiva ZIP
zip -r react-notificari-complete.zip . -x "*.log" "*.tmp" "*node_modules*" "*.git*"

echo "✅ Aplicația a fost împachetată cu succes!"
echo "📍 Locația arhivei: /tmp/react-notificari-export/react-notificari-complete.zip"

# Afișează informații despre arhivă
ls -lh /tmp/react-notificari-export/react-notificari-complete.zip

echo ""
echo "🔍 Conținutul arhivei:"
unzip -l /tmp/react-notificari-export/react-notificari-complete.zip | head -20

echo ""
echo "📥 Pentru descărcare, rulează:"
echo "   curl -o react-notificari-complete.zip file:///tmp/react-notificari-export/react-notificari-complete.zip"