#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

status=0

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

all_files_list="$tmp_dir/all_files.txt"
doc_files_list="$tmp_dir/doc_files.txt"
code_files_list="$tmp_dir/code_files.txt"

collect_files() {
  find . -type f \
    \( -name "*.md" -o -name "*.dart" -o -name "*.sh" -o -name "*.yaml" -o -name "*.yml" \) \
    ! -path "./.git/*" \
    ! -path "./.dart_tool/*" \
    ! -path "./build/*" \
    ! -path "./coverage/*" \
    ! -path "./assets/build/*" \
    ! -path "./android/build/*" \
    ! -path "./ngl_flutter/build/*" \
    ! -path "./ngl_flutter/example/build/*" \
    ! -path "./ios/Pods/*" \
    ! -path "./lib/l10n/app_localizations*.dart" \
    ! -path "./lib/core/navigation/app_router.gr.dart" \
    ! -path "./lib/features/auth/presentation/logic/auth/cubit/auth_cubit.freezed.dart" \
    ! -path "./ngl_flutter/assets/ngl_viewer/ngl.js" \
    ! -path "./tool/check_text_quality.sh" \
    ! -name "*.g.dart"
}

collect_files | sort > "$all_files_list"

if [[ ! -s "$all_files_list" ]]; then
  echo "No files found for text quality checks."
  exit 1
fi

grep -E '\.md$' "$all_files_list" > "$doc_files_list" || true
grep -E '\.(dart|sh|yaml|yml)$' "$all_files_list" > "$code_files_list" || true

run_check() {
  local label="$1"
  local pattern="$2"
  local file_list="$3"
  shift 3
  local report="$tmp_dir/${label}.txt"

  if [[ ! -s "$file_list" ]]; then
    echo "[PASS] ${label}"
    return
  fi

  if tr '\n' '\0' < "$file_list" | xargs -0 rg -n --color=never "$@" -e "$pattern" > "$report"; then
    echo "[FAIL] ${label}"
    sed -n '1,120p' "$report"
    status=1
  else
    echo "[PASS] ${label}"
  fi
}

echo "Running text quality checks..."

forbidden_typography_pattern=$'[\u2014\u2013\u201C\u201D\u2018\u2019\u2026]'
run_check "forbidden_typography" "$forbidden_typography_pattern" "$all_files_list" -S
run_check "non_english_docs" '[А-Яа-яЁё]' "$doc_files_list" -S
run_check "non_english_comments" '(^\s*//.*[А-Яа-яЁё])|(^\s*///.*[А-Яа-яЁё])|(/\*.*[А-Яа-яЁё].*\*/)' "$code_files_list" -S
run_check "ai_trace_mentions" '(generated by ai|generated with ai|written by ai|as an ai|chatgpt|copilot|llm-generated)' "$all_files_list" -Si
run_check "placeholder_logs" 'STAGE LOG' "$all_files_list" -S

if [[ $status -ne 0 ]]; then
  echo "Text quality checks failed."
  exit 1
fi

echo "All text quality checks passed."
