#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

TMP_PATTERNS="$(mktemp)"
trap 'rm -f "$TMP_PATTERNS"' EXIT

printf '%s\n' \
  'Generated by ChatGPT' \
  'Generated by Replit' \
  'Generated by Copilot' \
  'AI-generated' \
  'created by an AI' \
  'lorem ipsum' \
  'Replit' > "$TMP_PATTERNS"

rg -n -f "$TMP_PATTERNS" . \
  --hidden \
  --glob '!/.git/**' \
  --glob '!node_modules/**' \
  --glob '!**/node_modules/**' \
  --glob '!.venv/**' \
  --glob '!dist/**' \
  --glob '!**/dist/**' \
  --glob '!build/**' \
  --glob '!**/build/**' \
  --glob '!coverage/**' \
  --glob '!pnpm-lock.yaml' \
  --glob '!tools/verify_no_ai_traces.sh' \
  --glob '!lib/api-client-react/src/generated/**' \
  --glob '!lib/api-client-react/dist/**' \
  --glob '!lib/api-zod/src/generated/**' \
  --glob '!lib/api-zod/dist/**' \
  --glob '!*.png' \
  --glob '!*.jpg' \
  --glob '!*.jpeg' \
  --glob '!*.gif' \
  --glob '!*.ico' && {
    echo "Authored-file provenance audit failed."
    exit 1
  }

echo "Authored-file provenance audit passed."
