#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

STAGED_RS_FILES=$(git diff --cached --name-only --diff-filter=ACMR -- '*.rs' || true)
HAS_MANIFEST_CHANGES=0
if git diff --cached --name-only --diff-filter=ACMR -- 'Cargo.toml' | grep -q .; then
  HAS_MANIFEST_CHANGES=1
fi

if [ -z "$STAGED_RS_FILES" ] && [ "$HAS_MANIFEST_CHANGES" -eq 0 ]; then
  exit 0
fi

ERRORS=0

check_staged() {
  local pattern="$1"
  local description="$2"
  local non_test_only="${3:-0}"

  local matches=""
  while IFS= read -r file; do
    [ -n "$file" ] || continue
    local result
    result=$(git show ":$file" 2>/dev/null | grep -nE "$pattern" || true)
    if [ "$non_test_only" = "1" ]; then
      result=$(printf '%s\n' "$result" | grep -vE '#\[cfg\(test\)\]|#\[test\]|mod tests|reason = |".*unwrap|".*expect' || true)
    fi
    if [ -n "$result" ]; then
      matches="$matches"$'\n'"  $file: $result"
    fi
  done <<< "$STAGED_RS_FILES"

  if [ -n "$matches" ]; then
    echo "FAIL: $description" >&2
    echo "$matches" >&2
    echo "" >&2
    ERRORS=$((ERRORS + 1))
  fi
}

echo "Running iced-rust-desktop pre-commit checks..."
echo "  Checking staged Rust content..."

check_staged '\.unwrap\(\)' 'No .unwrap() in production code — handle the error or propagate it with context' 1
check_staged '\.expect\(' 'No .expect() in production code — handle the error or propagate it with context' 1
check_staged 'println!\(|eprintln!\(' 'No println!/eprintln! in committed Rust code — use tracing or a deliberate logging path' 0
check_staged '#\[allow\(' 'No #[allow(...)] — prefer #[expect(..., reason = "...")] when suppression is justified' 0
check_staged '(/Users/[a-z]|/home/[a-z]|C:\\\\|/opt/homebrew/)' 'No hardcoded user or system paths in Rust source' 0
check_staged '(Anthropic|AI-generated|AI-assisted|generated by AI|written by AI|co-authored.*AI|language model)' 'No AI attribution or generation notes in committed Rust source' 0

if [ "$ERRORS" -ne 0 ]; then
  exit 1
fi

if [ ! -f Cargo.toml ]; then
  exit 0
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "FAIL: cargo is required for Rust pre-commit checks." >&2
  exit 1
fi

if [ "${RUST_ICED_PRECOMMIT_RUN_FMT:-1}" = "1" ]; then
  echo "  Running cargo fmt --check..."
  cargo fmt --all --check
fi

if [ "${RUST_ICED_PRECOMMIT_RUN_CLIPPY:-1}" = "1" ]; then
  echo "  Running cargo clippy..."
  cargo clippy --all-targets --all-features -- -D warnings
fi

if [ "${RUST_ICED_PRECOMMIT_RUN_TESTS:-0}" = "1" ]; then
  echo "  Running cargo test --lib..."
  cargo test --lib
fi

exit 0
