#!/usr/bin/env bash
# Generated by Copilot
set -euo pipefail

cd "$(dirname "$0")"

echo "📦 Packaging extension..."
vsce package --no-git-tag-version

VSIX=$(ls -t *.vsix | head -1)
echo "📥 Installing $VSIX..."
code --install-extension "$VSIX"

echo "✅ Done. Reload VS Code to activate the updated extension."
