#!/usr/bin/env bash
# continual-learning-init.sh
# Initialize continual learning in any project
# Usage: curl -fsSL https://raw.githubusercontent.com/VenTheZone/lesson_learned/main/init.sh | bash

set -e

echo "🚀 Initializing Continual Learning workflow..."

# Create directory structure
mkdir -p .opencode/memory
mkdir -p .opencode/command
mkdir -p .opencode/skill
mkdir -p .opencode/command/templates

cp .opencode/command/templates/activity_log_template.md .opencode/memory/activity_log.md
cp .opencode/command/templates/config_template.json .opencode/config.json

cat > .opencode/memory/lessons_learned.md << 'EOF'
# Lessons Learned

*Project: [Your Project Name]*
*Last Updated: $(date +%Y-%m-%d)*
*Knowledge Base Version: 1.0*

---

## 📚 Do's (Best Practices)

*Use this section to document successful patterns and approaches.*

### General
<!-- Add entries like: "Always use async/await for database operations" -->

### Code Quality
<!-- Add entries like: "Write unit tests before implementing features" -->

### Architecture
<!-- Add entries like: "Separate business logic from presentation layer" -->

---

## ❌ Don'ts (Pitfalls to Avoid)

*Use this section to document mistakes to prevent repeating them.*

### Common Mistakes
<!-- Add entries like: "Don't forget to handle null values from API responses" -->

### Anti-patterns
<!-- Add entries like: "Don't nest callbacks - use promises or async/await" -->

### Configuration
<!-- Add entries like: "Don't hardcode API keys - use environment variables" -->

---

## ⚠️ Edge Cases & Gotchas

*Use this section for specific edge cases, platform-specific issues, and subtle bugs.*

### Platform-Specific
<!-- Add entries like: "Windows file paths need double backslashes" -->

### Race Conditions
<!-- Add entries like: "File read can fail if write hasn't flushed yet" -->

### Performance
<!-- Add entries like: "Large file operations can cause memory issues" -->

---

## 🔧 Project-Specific Patterns

*Use this section for project-specific conventions and decisions.*

### File Structure
<!-- Add entries like: "Components go in src/components/" -->

### Naming Conventions
<!-- Add entries like: "Use camelCase for JavaScript, snake_case for Python" -->

### API Patterns
<!-- Add entries like: "REST endpoints use /api/v1/ prefix" -->

---

## 🎯 Recent Insights

*Entries auto-generated by /smart-task command*

### $(date +%Y-%m-%d)
<!-- Example entry:
**Issue**: Forgot to close database connection
**Lesson**: Always wrap DB operations in try/finally to ensure connection cleanup
**Category**: Don'ts
-->

---

*Tip: Use `/smart-task` command to automatically add entries to this file after completing tasks.*
EOF

# Create smart-task command
cat > .opencode/command/smart-task.md << 'EOF'
---
description: Execute task with continual learning - read lessons, perform task, reflect, and update knowledge base
agent: build
model: anthropic/claude-3-5-sonnet-20241022
---

# Smart Task with Continual Learning

You are executing a task with Continual Learning workflow enabled. This ensures you learn from each task and improve future performance.

## 📖 Phase 1: Context Loading (MANDATORY - DO THIS FIRST)

Before generating any code or making any changes, you MUST:

1. **Read lessons file**: Use `read` tool to read `.opencode/memory/lessons_learned.md`
2. **Analyze lessons**: Look for:
   - Related Do's that should guide your approach
   - Related Don'ts that you must avoid
   - Edge Cases relevant to the task
   - Project-specific patterns to follow
3. **Acknowledge learning**: Briefly summarize what lessons are relevant to this task

⚠️ **DO NOT proceed to execution until you have read and acknowledged the lessons.**

---

## ⚙️ Phase 2: Task Execution

Execute the user's requested task, keeping the lessons in mind:

1. Apply relevant Do's and patterns
2. Avoid documented Don'ts and anti-patterns
3. Consider documented Edge Cases
4. Follow Project-Specific Patterns

If you discover a new pattern, insight, or make a mistake during execution, take note of it for the reflection phase.

---

## 🤔 Phase 3: Retrospective & Reflection (MANDATORY)

After completing the task, you MUST reflect on the experience:

1. **Was the task successful?**
   - Did everything work as expected?
   - Were there any issues or errors?

2. **Did you learn anything new?**
   - Did you discover a new pattern or approach?
   - Did you encounter an edge case not documented?

3. **Did lessons help?**
   - Did the knowledge base help you avoid a mistake?
   - Were any lessons particularly relevant?

4. **What should be documented?**
   - Any new patterns discovered?
   - Any mistakes made that others should avoid?
   - Any edge cases encountered?

---

## 📝 Phase 4: Update Knowledge Base (If Applicable)

If ANY of the following occurred, you MUST update `.opencode/memory/lessons_learned.md`:

### When to Update:
- ✅ You discovered a new best practice (Add to "Do's")
- ✅ You made a mistake that should be avoided (Add to "Don'ts")
- ✅ You encountered a tricky edge case (Add to "Edge Cases & Gotchas")
- ✅ You learned about a project-specific pattern (Add to "Project-Specific Patterns")

### Format for New Entries:
Add entries under the appropriate section using this format:

```
### [Date]

**Issue**: [Brief description of what happened or was learned]

**Lesson**: [Concise explanation of what to do or avoid]

**Example**: [Optional - short code snippet or example]

**Impact**: [Optional - why this matters]
```

### How to Update:
1. Read the current `lessons_learned.md` file
2. Append your new entry to the appropriate section
3. Update the "Last Updated" date at the top
4. Use the `write` tool to save the updated file

---

## 🎯 The Goal

Continual Learning means:
- Every task makes you smarter
- Every mistake becomes a lesson
- Every success becomes a pattern
- Future tasks benefit from past experience

**Remember**: This is a loop. Each task improves the knowledge base, which in turn improves future task execution.

---

*Knowledge is cumulative. Keep learning!*
EOF

# Create continual-learning skill
mkdir -p .opencode/skill/continual-learning
cat > .opencode/skill/continual-learning/SKILL.md << 'EOF'
name: continual-learning
description: Apply continual learning workflow - learn from each task to prevent repeating mistakes and build project knowledge

# Continual Learning Workflow

This skill enables AI agents to learn from tasks and build persistent knowledge for continuous improvement.

## Core Principle

**Read → Act → Record Loop**

Before any task: Read relevant lessons
During task: Apply lessons
After task: Record new insights

---

## 📖 Phase 1: Pre-Task Reading

Before executing any task:

1. **Read lessons file**: `.opencode/memory/lessons_learned.md`
2. **Search for relevance**:
   - Do's that apply to this task type
   - Don'ts that are warnings
   - Edge Cases relevant to the tech stack
   - Project-Specific Patterns to follow

3. **Acknowledge context**: Briefly note relevant lessons

---

## ⚙️ Phase 2: During Task Execution

While working on the task:

1. **Apply documented patterns**: Use Do's as guidance
2. **Avoid known pitfalls**: Follow Don'ts warnings
3. **Consider edge cases**: Check Edge Cases section
4. **Note new learnings**: If you discover something new, remember it for Phase 3

---

## 🤔 Phase 3: Post-Task Reflection

After completing the task:

1. **Self-Review**: Did I:
   - Follow applicable Do's?
   - Avoid documented Don'ts?
   - Handle relevant Edge Cases?
   - Follow Project-Specific Patterns?

2. **New Discoveries**: Did I:
   - Find a new pattern worth repeating?
   - Encounter a tricky edge case?
   - Make a mistake that should be documented?

---

## 📝 Phase 4: Record Insights

If anything new was learned:

1. **Categorize the insight**:
   - Best practice → Add to "Do's"
   - Mistake to avoid → Add to "Don'ts"
   - Tricky behavior → Add to "Edge Cases"
   - Project pattern → Add to "Project-Specific"

2. **Write the entry**:
   ```
   ### 2025-XX-XX

   **Issue**: [What happened or was discovered]

   **Lesson**: [What should be done or avoided]

   **Example**: [Optional code snippet]

   **Impact**: [Why this matters]
   ```

3. **Update metadata**: Change "Last Updated" date

4. **Save the file** using the `write` tool

---

## When to Use This Skill

Use this skill when:
- Starting a new project
- Working on an existing codebase
- Debugging complex issues
- Making architectural decisions
- Onboarding team members

---

## Benefits

- **Reduced mistakes**: Learn from past errors
- **Faster onboarding**: Knowledge is documented
- **Better consistency**: Follow established patterns
- **Continuous improvement**: Each task adds value

---

*Remember: Every task is an opportunity to learn. Record the insights.*
EOF

cat > .gitignore << 'EOF'
# OpenCode cache and temporary files
.opencode/cache/
.opencode/tmp/

# Session logs (large and not needed for version control)
.opencode/sessions/

# Activity logs (auto-generated, too noisy for version control)
.opencode/memory/activity_log.md
.opencode/memory/activity_archive.md

# Node modules (if using Node.js in project)
node_modules/

# Environment files with sensitive data
.env
.env.local
*.env

# IDE and editor files
.vscode/
.idea/
*.swp
*.swo
*~

# OS files
.DS_Store
Thumbs.db

# Build artifacts
dist/
build/
*.log

# But keep the knowledge base and templates!
!.opencode/memory/lessons_learned.md
!.opencode/command/
!.opencode/skill/
EOF

# Create README
cat > README.md << 'EOF'
# Continual Learning Workflow

Automated knowledge capture for AI-assisted development. Every task learns from past experience to prevent repeating mistakes.

## Quick Start

### Initialize in any project:

```bash
# Option 1: Direct installation
git clone https://github.com/VenTheZone/lesson_learned.git
cp -r lesson_learned/.opencode .

# Option 2: One-line setup
curl -fsSL https://raw.githubusercontent.com/VenTheZone/lesson_learned/main/init.sh | bash

# Option 3: Manual
mkdir -p .opencode/{memory,command,skill}
# Copy files from this repo
```

## How It Works

### Read → Act → Record Loop

1. **Read**: Before any task, read `.opencode/memory/lessons_learned.md`
2. **Act**: Execute task applying documented lessons
3. **Record**: After task, update lessons with new insights

### Usage

```bash
# For explicit task execution
/smart-task "implement user authentication"

# For automatic behavior (load skill)
skill continual-learning
```

## File Structure

```
.opencode/
├── memory/
│   └── lessons_learned.md      # Knowledge base (tracked in git)
├── command/
│   └── smart-task.md          # Explicit task command
└── skill/
    └── continual-learning/
        └── SKILL.md           # Loadable skill
```

## Sections

- **📚 Do's**: Best practices and patterns to follow
- **❌ Don'ts**: Common mistakes and anti-patterns to avoid
- **⚠️ Edge Cases**: Platform-specific issues and gotchas
- **🔧 Project Patterns**: Project-specific conventions

## Benefits

✅ **No repeat mistakes**: Learn once, apply everywhere
✅ **Faster onboarding**: Knowledge is documented
✅ **Better consistency**: Follow established patterns
✅ **Continuous improvement**: Each task adds value
✅ **Zero friction**: Works automatically with OpenCode

## For Teams

Commit the `.opencode/` directory to share knowledge across the team. Every developer benefits from lessons learned.

## License

MIT - Use freely in any project
EOF

echo "✅ Continual Learning initialized!"
echo ""
echo "📝 Files created:"
echo "  - .opencode/memory/lessons_learned.md"
echo "  - .opencode/memory/activity_log.md (auto-generated, git-ignored)"
echo "  - .opencode/config.json (configuration)"
echo "  - .opencode/command/smart-task.md"
echo "  - .opencode/command/clean-activity.md"
echo "  - .opencode/command/templates/activity_log_template.md"
echo "  - .opencode/command/templates/config_template.json"
echo "  - .opencode/skill/continual-learning/SKILL.md"
echo "  - .gitignore"
echo "  - README.md"
echo ""
echo "🚀 Next steps:"
echo "  1. Review .opencode/memory/lessons_learned.md"
echo "  2. Customize .opencode/config.json for your preferences"
echo "  3. Use '/smart-task' for tasks or load 'skill continual-learning'"
echo "  4. Run '/clean-activity' to manage activity logs (auto-generated after tasks)"
echo "  5. Commit .opencode/ to share with your team (activity_log.md is ignored)"
