#!/usr/bin/env bash
# AiDIY Knowledge Base Daily Update Script
# Runs every day to: fetch latest AI news → update knowledge base → write blog → build → create PR
set -euo pipefail

PROJECT_DIR="/home/wy/projects/AiDIY"
BRANCH_PREFIX="docs/daily-update"
TODAY=$(date +%Y-%m-%d)
BRANCH_NAME="${BRANCH_PREFIX}-${TODAY}"
LOG_FILE="${PROJECT_DIR}/logs/daily-update-${TODAY}.log"

mkdir -p "${PROJECT_DIR}/logs"

log() { echo "[$(date '+%H:%M:%S')] $*" | tee -a "${LOG_FILE}"; }

# --- Step 1: Prepare Git Branch ---
log "=== Step 1: Preparing git branch ==="
cd "${PROJECT_DIR}"
git fetch origin main
git checkout main
git reset --hard origin/main
git checkout -b "${BRANCH_NAME}" 2>/dev/null || git checkout "${BRANCH_NAME}"
log "Branch: ${BRANCH_NAME}"

# --- Step 2: Update Knowledge Base (via Hermes cron prompt) ---
# This script is called BY the cron job; the AI agent does the actual content work
# The cron prompt instructs the agent to:
#   1. Search web for latest AI/Agent news
#   2. Update relevant docs/ files
#   3. Write a blog post
#   4. Build and create PR

log "=== Step 2: Content updates handled by AI agent ==="
log "The calling agent will handle content generation"

# --- Step 3: Build ---
log "=== Step 3: Building Docusaurus ==="
cd "${PROJECT_DIR}"
npm run build 2>&1 | tail -20 | tee -a "${LOG_FILE}"
BUILD_EXIT=${PIPESTATUS[0]}

if [ "${BUILD_EXIT}" -ne 0 ]; then
    log "❌ Build failed! Aborting PR."
    exit 1
fi
log "✅ Build successful"

# --- Step 4: Commit & Push ---
log "=== Step 4: Committing changes ==="
cd "${PROJECT_DIR}"
git add -A

# Check if there are changes to commit
if git diff --cached --quiet; then
    log "No changes to commit. Skipping PR."
    git checkout main
    exit 0
fi

git commit -m "docs: daily knowledge update ${TODAY}

Auto-generated by AiDIY daily update cron job.

- Updated knowledge base with latest AI/Agent developments
- New blog post for ${TODAY}"

git push -u origin "${BRANCH_NAME}" 2>&1 | tee -a "${LOG_FILE}"

# --- Step 5: Create PR ---
log "=== Step 5: Creating PR ==="
cd "${PROJECT_DIR}"

# Check if PR already exists
EXISTING_PR=$(gh pr list --head "${BRANCH_NAME}" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "${EXISTING_PR}" ]; then
    log "PR #${EXISTING_PR} already exists, updating..."
else
    gh pr create \
        --title "docs: 每日知识更新 ${TODAY}" \
        --body "## 🤖 每日自动更新 ${TODAY}

本 PR 由定时任务自动生成，包含以下更新：

- 🔍 获取最新 AI/Agent 行业动态
- 📝 更新知识库文档
- ✍️ 发布博客文章
- ✅ 已通过 Docusaurus 构建验证" \
        --base main \
        --head "${BRANCH_NAME}" 2>&1 | tee -a "${LOG_FILE}"
    log "✅ PR created"
fi

# Cleanup: switch back to main
git checkout main
log "=== Done! ==="
