#!/usr/bin/env bash
set -euo pipefail

patterns=(
  'Generated by ChatGPT'
  'Generated by Copilot'
  'AI-generated'
  'created by an AI'
  'assistant-style explanations'
  'watermark'
  'lorem ipsum'
)

status=0
for pattern in "${patterns[@]}"; do
  if grep -RIn --exclude=verify_no_ai_traces.sh --exclude-dir=node_modules --exclude-dir=.svelte-kit --exclude-dir=.venv --exclude-dir=.git "$pattern" . >/tmp/callsignal_trace_check.txt 2>/dev/null; then
    cat /tmp/callsignal_trace_check.txt
    status=1
  fi
done

exit "$status"
