#!/usr/bin/env bash
set -euo pipefail

# Manual push script generated by Copilot.
# Fill in the placeholder below, then run:
#   bash upload_dti_changes_manual_run.sh
#
# Required placeholder:
# - GITHUB_TOKEN: token with repo write access to lwnoc/lwnoc_dti_noc

REPO_DIR="/home/lgzhu/dev/noc_work/lwnoc_dti_noc"
OWNER="lwnoc"
REPO="lwnoc_dti_noc"
BRANCH="main"
GITHUB_USER="<FILL_IN_GITHUB_USERNAME>"
GITHUB_TOKEN="<FILL_IN_GITHUB_TOKEN>"

if [[ "$GITHUB_USER" == "<FILL_IN_GITHUB_USERNAME>" || "$GITHUB_TOKEN" == "<FILL_IN_GITHUB_TOKEN>" ]]; then
  echo "Please fill GITHUB_USER and GITHUB_TOKEN placeholders first."
  exit 1
fi

cd "$REPO_DIR"

echo "== Verify local commit to push =="
git --no-pager log --oneline -n 3

echo "== Verify token =="
LOGIN=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/user | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("login","INVALID"))')
echo "Token login: ${LOGIN}"
if [[ "$LOGIN" == "INVALID" ]]; then
  echo "Invalid token."
  exit 1
fi

echo "== Push commit via HTTPS =="
HTTPS_URL="https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${OWNER}/${REPO}.git"
git push "$HTTPS_URL" "$BRANCH":"$BRANCH"

echo "Push done."
