#!/bin/bash
# Shell Environment Installer
# Sets up zsh integration, prompts, aliases, and secrets management

set -euo pipefail

# Source common utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

#──────────────────────────────────────────────────────────────────────────────
# Constants
#──────────────────────────────────────────────────────────────────────────────

ZSHRC_MARKER_START="# >>> aiteamforge initialize >>>"
ZSHRC_MARKER_END="# <<< aiteamforge initialize <<<"
ZSHRC_BACKUP_SUFFIX=".aiteamforge-backup"

#──────────────────────────────────────────────────────────────────────────────
# Helper Functions
#──────────────────────────────────────────────────────────────────────────────

# Resolve target zshrc — use ZSHRC_TARGET if set (for testing), else real HOME
_get_zshrc_path() {
    echo "${ZSHRC_TARGET:-$HOME/.zshrc}"
}

# Check if zshrc already has aiteamforge integration
has_zshrc_integration() {
    local zshrc
    zshrc="$(_get_zshrc_path)"
    if [ ! -f "$zshrc" ]; then
        return 1
    fi
    grep -q "$ZSHRC_MARKER_START" "$zshrc"
}

# Add aiteamforge sourcing block to zshrc
add_zshrc_integration() {
    local zshrc
    zshrc="$(_get_zshrc_path)"

    # Create zshrc if it doesn't exist
    if [ ! -f "$zshrc" ]; then
        info "Creating new .zshrc file"
        mkdir -p "$(dirname "$zshrc")"
        touch "$zshrc"
    fi

    # Back up existing zshrc
    if [ ! -f "${zshrc}${ZSHRC_BACKUP_SUFFIX}" ]; then
        info "Backing up existing .zshrc to ${zshrc}${ZSHRC_BACKUP_SUFFIX}"
        cp "$zshrc" "${zshrc}${ZSHRC_BACKUP_SUFFIX}"
    fi

    # Add integration block
    info "Adding aiteamforge integration to .zshrc"
    cat >> "$zshrc" << EOF

$ZSHRC_MARKER_START
# AITeamForge Environment Loader
# Auto-generated by aiteamforge installer
if [ -f "$AITEAMFORGE_DIR/share/aiteamforge-env.sh" ]; then
    source "$AITEAMFORGE_DIR/share/aiteamforge-env.sh"
fi
$ZSHRC_MARKER_END
EOF

    success "Added aiteamforge integration to .zshrc"
}

# Remove aiteamforge integration from zshrc
remove_zshrc_integration() {
    local zshrc
    zshrc="$(_get_zshrc_path)"

    if [ ! -f "$zshrc" ]; then
        return 0
    fi

    if ! has_zshrc_integration; then
        return 0
    fi

    info "Removing aiteamforge integration from .zshrc"

    # Remove the block between markers (including markers)
    sed -i.tmp "/$ZSHRC_MARKER_START/,/$ZSHRC_MARKER_END/d" "$zshrc"
    rm -f "${zshrc}.tmp"

    success "Removed aiteamforge integration from .zshrc"
}

# Install environment loader script
install_env_loader() {
    local template="$INSTALL_ROOT/share/templates/aiteamforge-env.sh"
    local target="$AITEAMFORGE_DIR/share/aiteamforge-env.sh"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing environment loader"

    # Substitute variables in template
    sed -e "s|{{AITEAMFORGE_DIR}}|$AITEAMFORGE_DIR|g" \
        "$template" > "$target"

    chmod +x "$target"
    success "Installed environment loader"
}

# Install prompt configuration
install_prompt() {
    local template="$INSTALL_ROOT/share/templates/aiteamforge-prompt.sh"
    local target="$AITEAMFORGE_DIR/share/aiteamforge-prompt.sh"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing prompt configuration"

    # Copy template (no substitution needed for prompt)
    cp "$template" "$target"
    chmod +x "$target"

    success "Installed prompt configuration"
}

# Install shell aliases
install_aliases() {
    local aliases_dir="$AITEAMFORGE_DIR/share/aliases"
    mkdir -p "$aliases_dir"

    info "Installing shell aliases"

    # Install each alias file
    # Note: kanban-aliases.sh is intentionally omitted — kanban-helpers.sh
    # (installed by install-kanban.sh) is sourced directly from aiteamforge-env.sh
    # and provides the full kb-* function set.
    for alias_file in agent-aliases.sh cc-aliases.sh worktree-aliases.sh; do
        local template="$INSTALL_ROOT/share/templates/aliases/$alias_file"
        local target="$aliases_dir/$alias_file"

        if [ ! -f "$template" ]; then
            warning "Template not found: $template (skipping)"
            continue
        fi

        # Substitute variables in template
        sed -e "s|{{AITEAMFORGE_DIR}}|$AITEAMFORGE_DIR|g" \
            "$template" > "$target"

        chmod +x "$target"
    done

    success "Installed shell aliases"
}

# Install helper scripts (update_claude_agent.sh, etc.)
install_helper_scripts() {
    local scripts_src="$INSTALL_ROOT/share/scripts"

    info "Installing helper scripts"

    # update_claude_agent.sh — updates tmux status bar with current agent name
    # Used by claude-* alias functions in agent-aliases.sh
    local agent_script_src="$scripts_src/update_claude_agent.sh"
    local agent_script_dest="$AITEAMFORGE_DIR/update_claude_agent.sh"
    if [ -f "$agent_script_src" ]; then
        cp "$agent_script_src" "$agent_script_dest"
        chmod +x "$agent_script_dest"
    else
        warning "update_claude_agent.sh not found at: $agent_script_src (skipping)"
    fi

    # Copy scripts/ directory so team startup scripts can find agent-panel-display.sh,
    # iterm2_window_manager.py, and other runtime helpers at $AITEAMFORGE_DIR/scripts/
    local scripts_dest="$AITEAMFORGE_DIR/scripts"
    mkdir -p "$scripts_dest"
    for helper in agent-panel-display.sh display-agent-avatar.sh iterm2_window_manager.py \
                  set-lcars-profile-browser.py create-lcars-profile.py lcars-tmp-dir.sh \
                  kanban-backup.py fleet-reporter.sh init-agent-panel-json.py; do
        if [ -f "$scripts_src/$helper" ]; then
            cp "$scripts_src/$helper" "$scripts_dest/$helper"
            chmod +x "$scripts_dest/$helper"
        fi
    done

    success "Installed helper scripts"
}

# Install worktree-helpers.sh — provides wt-current, wt-project status-name/code/short,
# and related wt-* functions required by all team banners. Without this file present at
# $AITEAMFORGE_DIR/worktree-helpers.sh, banners fail with command-not-found on tap installs.
# (XACA-0494: was missing from tap install manifest; worktree-aliases.sh is insufficient)
install_worktree_helpers() {
    local src="$INSTALL_ROOT/share/scripts/worktree-helpers.sh"
    local target="$AITEAMFORGE_DIR/worktree-helpers.sh"

    if [ ! -f "$src" ]; then
        warning "worktree-helpers.sh not found at: $src (skipping)"
        return 0
    fi

    info "Installing worktree helper functions"
    cp "$src" "$target"
    chmod +x "$target"
    success "Installed: $target"
}

# Install secrets template
install_secrets_template() {
    local template="$INSTALL_ROOT/share/templates/secrets.env.template"
    local target="$AITEAMFORGE_DIR/secrets.env.template"
    local secrets_file="$AITEAMFORGE_DIR/secrets.env"

    if [ ! -f "$template" ]; then
        error "Template not found: $template"
        return 1
    fi

    info "Installing secrets template"

    # Copy template
    cp "$template" "$target"

    # Check if actual secrets file exists
    if [ -f "$secrets_file" ]; then
        warning "Secrets file already exists at $secrets_file"
        info "Review $target for expected variables"
    else
        warning "No secrets file found"
        info "Copy $target to $secrets_file and populate with your credentials"
        info "NEVER commit the actual secrets.env file to git"
    fi

    success "Installed secrets template"
}

# Create Python virtual environment and install iterm2 module
install_python_venv() {
    local venv_dir="${HOME}/.aiteamforge/venv"

    info "Setting up Python virtual environment"

    # Check Python3 is available
    if ! command -v python3 &>/dev/null; then
        warning "python3 not found — skipping venv setup"
        warning "Install Python 3 (brew install python3) and re-run setup to enable iTerm2 integration"
        return 0
    fi

    # Verify python3 can create venvs (venv module may be missing on some systems)
    if ! python3 -m venv --help &>/dev/null; then
        warning "python3 venv module not available — skipping venv setup"
        warning "Install python3-venv or use a full Python installation"
        return 0
    fi

    # Create the venv directory (idempotent — venv handles existing dirs)
    mkdir -p "$(dirname "$venv_dir")"
    if ! python3 -m venv "$venv_dir" 2>/dev/null; then
        warning "Failed to create Python venv at $venv_dir — skipping"
        return 0
    fi

    info "Installing iterm2 Python module"

    # Use the venv's pip to install the iterm2 package
    local pip_bin="${venv_dir}/bin/pip"
    if [ ! -x "$pip_bin" ]; then
        warning "pip not found in venv — skipping iterm2 install"
        return 0
    fi

    if ! "$pip_bin" install --quiet iterm2 2>/dev/null; then
        warning "Failed to install iterm2 Python module — you can retry manually:"
        warning "  ${venv_dir}/bin/pip install iterm2"
        return 0
    fi

    success "Python venv created at $venv_dir with iterm2 module installed"
    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Main Installation Function
#──────────────────────────────────────────────────────────────────────────────

install_shell_environment() {
    header "Installing Shell Environment"

    # Check if already installed
    if has_zshrc_integration; then
        warning "Shell integration already exists in .zshrc"
        if ! prompt_yes_no "Reinstall shell environment?" "n"; then
            info "Skipping shell environment installation"
            return 0
        fi
        # Remove and reinstall
        remove_zshrc_integration
    fi

    # Create necessary directories
    mkdir -p "$AITEAMFORGE_DIR/share"

    # Install components
    install_env_loader || return 1
    install_prompt || return 1
    install_aliases || return 1
    install_helper_scripts || return 1
    install_worktree_helpers  # non-fatal; banners fall back to stubs if missing
    install_secrets_template || return 1

    # Set up Python venv with iterm2 module (non-fatal if Python unavailable)
    install_python_venv

    # Install iTerm2 shell integration (imgcat, it2setkeylabel, etc.)
    # This prevents "Allow Terminal-Initiated Display?" prompts for inline images
    if [ ! -f "$HOME/.iterm2_shell_integration.zsh" ]; then
        info "Installing iTerm2 shell integration..."
        curl -sSL https://iterm2.com/shell_integration/install_shell_integration.sh | bash 2>/dev/null
        if [ -f "$HOME/.iterm2_shell_integration.zsh" ]; then
            success "iTerm2 shell integration installed"
            # Also install imgcat utility if not already present
            if [ ! -f "$HOME/.iterm2/imgcat" ]; then
                mkdir -p "$HOME/.iterm2"
                curl -sSL https://iterm2.com/utilities/imgcat -o "$HOME/.iterm2/imgcat" 2>/dev/null
                chmod +x "$HOME/.iterm2/imgcat" 2>/dev/null
            fi
        else
            warning "iTerm2 shell integration failed — inline images may prompt for permission"
        fi
    else
        success "iTerm2 shell integration already installed"
    fi

    # Suppress iTerm2 permission prompts for inline images and display changes.
    # imgcat uses the 1337;File= protocol which iTerm2 treats as a "download" —
    # without these prefs, every imgcat call triggers "Allow?" dialogs.
    if command -v defaults &>/dev/null; then
        defaults write com.googlecode.iterm2 NoSyncSuppressDownloadConfirmation -bool true 2>/dev/null
        defaults write com.googlecode.iterm2 NoSyncSuppressBroadcastInputWarning -bool true 2>/dev/null
    fi

    # Add zshrc integration
    add_zshrc_integration || return 1

    success "Shell environment installed successfully"

    info ""
    info "Next steps:"
    info "  1. Review secrets template: $AITEAMFORGE_DIR/secrets.env.template"
    info "  2. Create secrets file: cp secrets.env.template secrets.env"
    info "  3. Populate secrets.env with your credentials"
    info "  4. Reload your shell: source ~/.zshrc"
    info ""

    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Uninstall Function
#──────────────────────────────────────────────────────────────────────────────

uninstall_shell_environment() {
    header "Uninstalling Shell Environment"

    # Remove zshrc integration
    remove_zshrc_integration

    # Remove installed files
    info "Removing shell environment files"
    rm -f "$AITEAMFORGE_DIR/share/aiteamforge-env.sh"
    rm -f "$AITEAMFORGE_DIR/share/aiteamforge-prompt.sh"
    rm -rf "$AITEAMFORGE_DIR/share/aliases"
    rm -f "$AITEAMFORGE_DIR/update_claude_agent.sh"
    rm -f "$AITEAMFORGE_DIR/secrets.env.template"

    success "Shell environment uninstalled"

    # Restore backup if it exists
    local zshrc
    zshrc="$(_get_zshrc_path)"
    if [ -f "${zshrc}${ZSHRC_BACKUP_SUFFIX}" ]; then
        info "Backup available at: ${zshrc}${ZSHRC_BACKUP_SUFFIX}"
        if prompt_yes_no "Restore backup?" "n"; then
            cp "${zshrc}${ZSHRC_BACKUP_SUFFIX}" "$zshrc"
            success "Restored .zshrc from backup"
        fi
    fi

    return 0
}

#──────────────────────────────────────────────────────────────────────────────
# Export functions for setup wizard
#──────────────────────────────────────────────────────────────────────────────

# This script is sourced by the setup wizard, so export the functions
# NOTE: The wrapper in aiteamforge-setup.sh calls _run_shell_installer
# to avoid name collision with install_shell_environment defined here.
_run_shell_installer() { install_shell_environment; }
_run_shell_uninstaller() { uninstall_shell_environment; }
export -f install_shell_environment
export -f uninstall_shell_environment
export -f install_python_venv
export -f _run_shell_installer
export -f _run_shell_uninstaller
