#!/usr/bin/env bash
# Void Linux UEFI Full-Disk-Encryption Installer (Interactive, Using Host Repo)
# Author: Generated by ChatGPT
# Description: Install Void Linux with UEFI and LUKS encryption using the host system's XBPS repository.

set -euo pipefail
IFS=$'\n\t'

### Helpers ###
log() { echo -e "[\e[32mINFO\e[0m] $*"; }
err() { echo -e "[\e[31mERROR\e[0m] $*" >&2; exit 1; }
prompt(){ local v="$1" t="$2" d="$3"; read -rp "$t [$d]: " i; eval "$v=\"${i:-$d}\""; }

### Step 0: Update Host System & Install Tools ###
update_system(){
  log "Syncing and updating XBPS on host..."
  xbps-install -Sy
  xbps-install -uy xbps
  log "Installing xtools and parted for xgenfstab and disk partitioning..."
  xbps-install -Sy xtools parted
}

### Step 1: Ask for Hostname and Root Password ###
get_host_and_pass(){
  prompt hostname "Enter the hostname for the new system" "voidlinux"
  while true; do
    read -rsp "Enter root password: " root_pw; echo
    read -rsp "Confirm root password: " root_pw_confirm; echo
    [[ "$root_pw" == "$root_pw_confirm" ]] && break
    echo "Passwords do not match, try again." >&2
  done
}

### Step 2: Select Disk ###
select_disk(){
  log "Available disks:"
  lsblk -dpno NAME,SIZE,MODEL | grep -E "/dev/[sv]d|/dev/nvme"
  prompt disk "Enter the disk to install on" "/dev/sda"
  [[ -b "$disk" ]] || err "Disk $disk not found."
}

### Step 3: Enter Partition Sizes ###
define_sizes(){
  prompt esp_size  "EFI partition size in MiB" "128"
  prompt root_lv   "Root LV size in GiB"   "10"
  prompt swap_lv   "Swap LV size in GiB"   "2"
}

### Step 4: Partition Disk ###
partition_disk(){
  log "Creating GPT and partitions on $disk..."
  parted --script "$disk" mklabel gpt
  parted --script "$disk" mkpart ESP fat32 1MiB ${esp_size}MiB
  parted --script "$disk" set 1 esp on
  parted --script "$disk" mkpart primary ext4 ${esp_size}MiB 100%
  esp="${disk}1"
  cryptpart="${disk}2"
}

### Step 5: Setup LUKS ###
setup_luks(){
  log "Formatting ${cryptpart} as LUKS1 and opening..."
  cryptsetup luksFormat --type luks1 "$cryptpart"
  cryptsetup luksOpen "$cryptpart" cryptroot
}

### Step 6: Create LVM ###
setup_lvm(){
  log "Initializing LVM on /dev/mapper/cryptroot..."
  pvcreate /dev/mapper/cryptroot
  vgcreate voidvg /dev/mapper/cryptroot
  lvcreate -L "${root_lv}G" -n root voidvg
  lvcreate -L "${swap_lv}G" -n swap voidvg
  lvcreate -l 100%FREE -n home voidvg
}

### Step 7: Format Filesystems ###
format_filesystems(){
  log "Formatting filesystems..."
  mkfs.fat -F32 "$esp"
  mkfs.xfs /dev/voidvg/root
  mkfs.xfs /dev/voidvg/home
  mkswap /dev/voidvg/swap && swapon /dev/voidvg/swap
}

### Step 8: Mount Filesystems ###
mount_all(){
  log "Mounting filesystems..."
  mount /dev/voidvg/root /mnt
  mkdir -p /mnt/{boot/efi,home}
  mount "$esp" /mnt/boot/efi
  mount /dev/voidvg/home /mnt/home
}

### Step 9: Copy XBPS Keys ###
copy_keys(){
  log "Copying XBPS keys into chroot..."
  mkdir -p /mnt/var/db/xbps/keys
  cp -r /var/db/xbps/keys/* /mnt/var/db/xbps/keys/
}

### Step 10: Install Base System ###
install_base(){
  log "Installing base system and tools..."
  xbps-install -Sy -r /mnt \
    base-system lvm2 cryptsetup grub grub-x86_64-efi xtools parted
}

### Step 11: Generate fstab ###
make_fstab(){
  log "Generating /mnt/etc/fstab..."
  xgenfstab /mnt > /mnt/etc/fstab
}

### Step 12: Initial Chroot Configuration ###
configure_chroot_initial(){
  log "Entering chroot for initial configuration..."
  xchroot /mnt /bin/bash -euo pipefail <<EOF
# Set hostname
echo "${hostname}" > /etc/hostname
# Set root password
echo "root:${root_pw}" | chpasswd
# Configure locale
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "en_US.UTF-8 UTF-8" >> /etc/default/libc-locales
xbps-reconfigure -f glibc-locales
# Enable GRUB cryptodisk support
sed -i 's/^#GRUB_ENABLE_CRYPTODISK=/GRUB_ENABLE_CRYPTODISK=y/' /etc/default/grub
# Update GRUB cmdline with LUKS UUID
uuid=\$(blkid -s UUID -o value $cryptpart)
sed -i "s|GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"rd.luks.uuid=\$uuid\"|" /etc/default/grub
# Create keyfile
dd bs=1 count=64 if=/dev/urandom of=/boot/volume.key
chmod 000 /boot/volume.key
EOF
}

### Step 13: Interactive LUKS Key Addition ###
add_luks_keyfile(){
  log "Interactive LUKS key addition inside chroot..."
  xchroot /mnt cryptsetup luksAddKey /dev/mapper/cryptroot /boot/volume.key
}

### Step 14: Final Chroot Configuration ###
configure_chroot_final(){
  log "Final chroot tasks..."
  xchroot /mnt /bin/bash -euo pipefail <<EOF
# Write crypttab and dracut config
echo "cryptroot UUID=\$uuid /boot/volume.key luks" > /etc/crypttab
echo 'install_items+=" /boot/volume.key /etc/crypttab "' > /etc/dracut.conf.d/10-crypt.conf
# Install GRUB and rebuild initramfs
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=void
xbps-reconfigure -fa
EOF
}

### Step 15: Cleanup & Reboot ###
cleanup(){
  log "Cleanup and rebooting..."
  umount -R /mnt
  reboot
}

### Main Flow ###
main(){
  update_system
  get_host_and_pass
  select_disk
  define_sizes
  partition_disk
  setup_luks
  setup_lvm
  format_filesystems
  mount_all
  copy_keys
  install_base
  make_fstab
  configure_chroot_initial
  add_luks_keyfile
  configure_chroot_final
  cleanup
}
main "$@"
