#!/usr/bin/env bash
# Generated by claude-onboarding-agent (skill: web-development-setup)
# Purpose: run tsc --noEmit on edited TS/TSX files and surface errors.
# Safe to delete — Claude Code will continue without the hook.
#
# Source template consumed by web-development-setup/SKILL.md at Step 8.
# At emission time the skill substitutes `<PM_EXEC>` with one of:
#   `pnpm exec`, `npm exec`, `yarn exec`, `bun x`
# (selected from Q4). Do not invoke this file directly — it is not on
# disk as an executable until the skill writes it under
# ./.claude/hooks/web-type-check.sh via skills/_shared/emit-hook.md.

set -u

INPUT=$(cat)
FILE=$(printf '%s' "$INPUT" | jq -r '.tool_input.file_path // .tool_response.filePath // empty' 2>/dev/null)
[ -z "$FILE" ] && exit 0

case "$FILE" in
  *.ts|*.tsx) : ;;
  *) exit 0 ;;
esac

cd "$CLAUDE_PROJECT_DIR" 2>/dev/null || exit 0
[ -f tsconfig.json ] || exit 0

OUT=$(<PM_EXEC> tsc --noEmit --pretty false "$FILE" 2>&1)
STATUS=$?
[ "$STATUS" -eq 0 ] && exit 0

MSG=$(printf '%s\n' "$OUT" | head -n 30)
jq -cn --arg ctx "tsc reported errors after editing $FILE:\n$MSG" \
  '{hookSpecificOutput: {hookEventName: "PostToolUse", additionalContext: $ctx}}'
exit 0
