#!/usr/bin/env bash
# skills-fix.sh - Auto-fix critical Claude Skills issues
# Generated by Claude Skills Detective
# Run: chmod +x skills-fix.sh && ./skills-fix.sh

set -e

echo "🕵️ Claude Skills Detective - Auto-Fix Script"
echo "=============================================="
echo ""

cd /home/sk/medellin-spark

# Fix #1: Delete empty supabase-connect folder
echo "🔧 Fix #1: Removing empty supabase-connect folder..."
if [ -d ".claude/skills/supabase-connect" ]; then
  if [ -z "$(ls -A .claude/skills/supabase-connect)" ]; then
    rmdir ".claude/skills/supabase-connect" && \
      echo "  ✅ Deleted: supabase-connect (empty folder)" || \
      echo "  ⚠️  Could not delete (check permissions)"
  else
    echo "  ⚠️  Folder not empty - skipping (manual review needed)"
  fi
else
  echo "  ℹ️  Already clean (folder doesn't exist)"
fi

# Fix #2: Consolidate playwright skills
echo ""
echo "🔧 Fix #2: Consolidating playwright-e2e skills..."
if [ -d ".claude/skills/playwright-e2e" ] && [ -d ".claude/skills/playwright-e2e-skill" ]; then
  # Move SKILL.md from playwright-e2e to playwright-e2e-skill
  if [ -f ".claude/skills/playwright-e2e/SKILL.md" ]; then
    mv ".claude/skills/playwright-e2e/SKILL.md" ".claude/skills/playwright-e2e-skill/SKILL.md"
    echo "  ✅ Moved SKILL.md to playwright-e2e-skill"
  else
    echo "  ℹ️  SKILL.md already in correct location"
  fi
  
  # Delete old playwright-e2e folder
  if [ -d ".claude/skills/playwright-e2e" ]; then
    rm -rf ".claude/skills/playwright-e2e"
    echo "  ✅ Deleted duplicate: playwright-e2e"
  fi
  
  # Rename playwright-e2e-skill → playwright-e2e
  if [ -d ".claude/skills/playwright-e2e-skill" ]; then
    mv ".claude/skills/playwright-e2e-skill" ".claude/skills/playwright-e2e"
    echo "  ✅ Renamed: playwright-e2e-skill → playwright-e2e (consolidated)"
  fi
else
  echo "  ℹ️  Already consolidated"
fi

# Fix #3: Add version to chrome-dev-skill (if missing)
echo ""
echo "🔧 Fix #3: Adding version numbers to skills..."

CHROME_SKILL=".claude/skills/chrome-dev-skill/SKILL.md"
if [ -f "$CHROME_SKILL" ]; then
  if ! grep -q "^version:" "$CHROME_SKILL"; then
    # Add version after description line
    sed -i '/^description:/a version: 1.0.0' "$CHROME_SKILL"
    echo "  ✅ Added version to chrome-dev-skill"
  else
    echo "  ℹ️  chrome-dev-skill already has version"
  fi
else
  echo "  ⚠️  chrome-dev-skill/SKILL.md not found"
fi

# Verification
echo ""
echo "=============================================="
echo "✅ Auto-fix complete!"
echo ""
echo "📊 Verification Results:"
echo "------------------------"

# Count skills with SKILL.md
SKILL_COUNT=$(find .claude/skills -maxdepth 2 -name "SKILL.md" 2>/dev/null | wc -l)
echo "  Skills with SKILL.md: $SKILL_COUNT"

# Check for empty folders
EMPTY_FOLDERS=$(find .claude/skills -type d -empty 2>/dev/null | wc -l)
echo "  Empty folders: $EMPTY_FOLDERS"

# Check for playwright duplicates
PLAYWRIGHT_COUNT=$(ls -1d .claude/skills/playwright* 2>/dev/null | wc -l)
echo "  Playwright skills: $PLAYWRIGHT_COUNT (should be 1)"

echo ""
echo "🎯 Next Steps:"
echo "1. ✅ Review changes: git diff .claude/skills/"
echo "2. 📝 Update .claude/skills/README.md"
echo "3. 🧪 Test skills: 'Use the playwright-e2e skill to run smoke test'"
echo "4. 🔄 Re-run audit: Read CLAUDE_SKILLS_AGENT_AUDIT_REPORT.md"
echo ""
echo "System should now be 100% ready! 🚀"
echo ""

