#!/bin/bash
# src/tools/check_anonymity.sh
# Verifica violacoes de anonimato antes de commits
#
# PERMITE:
#   - Config de API (api_key, openai_key, etc)
#   - Formatos de dados (compativel com OpenAI/HuggingFace)
#   - Listas de deteccao/filtro
#   - Nomes de providers em config
#
# BLOQUEIA:
#   - Assinaturas (by Claude, feito por, autor:)
#   - Comentarios creditando IA
#   - Docstrings mencionando IA como autor

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "Verificando anonimato..."

VIOLATIONS=0

# 1. ASSINATURAS E CREDITOS (SEMPRE bloquear)
SIGNATURES=$(grep -rniE \
    "(feito por|criado por|autor:|written by|made by|credit to|generated by claude|by claude|by gpt|by anthropic|claude wrote|gpt wrote)" \
    src/ --include="*.py" 2>/dev/null \
    | grep -viE "caused by|sorted by|followed by|grouped by|filtered by|owned by|powered by|multiplied by|divided by" \
    || true)

if [ -n "$SIGNATURES" ]; then
    echo ""
    echo -e "${RED}========================================"
    echo "  ASSINATURAS DETECTADAS (BLOQUEADO)"
    echo -e "========================================${NC}"
    echo ""
    echo "$SIGNATURES"
    VIOLATIONS=1
fi

# 2. COMENTARIOS PUROS creditando IA (linhas que sao SO comentario)
# Exemplo bloqueado: "# Claude sugeriu isso"
# Exemplo permitido: "# API do claude" (contexto tecnico)
COMMENTS=$(grep -rniE "^[[:space:]]*#.*(claude|anthropic).*(sugeriu|escreveu|fez|criou|gerou|wrote|made|created)" src/ --include="*.py" 2>/dev/null || true)

if [ -n "$COMMENTS" ]; then
    echo ""
    echo -e "${RED}========================================"
    echo "  COMENTARIOS CREDITANDO IA (BLOQUEADO)"
    echo -e "========================================${NC}"
    echo ""
    echo "$COMMENTS"
    VIOLATIONS=1
fi

# Resultado
if [ $VIOLATIONS -gt 0 ]; then
    echo ""
    echo -e "${RED}COMMIT BLOQUEADO: Remova as violacoes acima${NC}"
    echo ""
    exit 1
fi

echo ""
echo -e "${GREEN}OK: Nenhuma violacao de anonimato${NC}"
exit 0
