#!/bin/zsh
set -euo pipefail

candidates=()
for f in *.mp3(N); do
  [[ -f "m4a/${f%.mp3}.m4a" ]] || candidates+=("$f")
done

if (( ${#candidates} == 0 )); then
  echo "All MP3 files are already converted."
  exit 0
fi

file=$(print -rl -- "${candidates[@]}" | fzf --prompt="Select an MP3 file: ")

basename="${file%.mp3}"

# if m4a directory doesn't exist, create it
mkdir -p m4a


# check if lyrics file exists
if [[ ! -f "$basename.txt" ]]; then
  echo "Lyrics file '$basename.txt' not found. Exiting."
  exit 1
fi

# if the output file exists, exit
if [[ -f "m4a/$basename.m4a" ]]; then
  echo "Output file 'm4a/$basename.m4a' already exists. Exiting."
  exit 1
fi

ffmpeg -i "$file" -c:a aac -b:a 256k "m4a/$basename.m4a"
AtomicParsley "m4a/$basename.m4a" --lyricsFile "$basename.txt" --overWrite
echo "Conversion complete: $basename.m4a with embedded lyrics."


# =============================================================================
# USER MANUAL (Auto generated by GPT-5.2)
# =============================================================================
#
# Purpose
# -------
# Convert MP3 files to M4A (AAC 256 kbps) and embed lyrics from a matching .txt file.
#
# Requirements
# ------------
# - zsh
# - fzf
# - ffmpeg
# - AtomicParsley
#
# Expected Files
# --------------
# - Audio:   <name>.mp3
# - Lyrics:  <name>.txt
# - Output:  m4a/<name>.m4a
#
# How It Works
# ------------
# 1. Scans the current directory for *.mp3 files
# 2. Excludes MP3s that already have m4a/<name>.m4a
# 3. Shows remaining files in an interactive fzf selector
# 4. Converts the selected MP3 to M4A
# 5. Embeds lyrics from the matching .txt file
#
# Behavior Notes
# --------------
# - Only one file is processed per run
# - The m4a/ directory is created automatically
# - The script exits if:
#   - no unconverted MP3 files exist
#   - the lyrics file is missing
#   - the output file already exists
#
# Usage
# -----
# chmod +x convert.sh
# ./convert.sh
#
# Output
# ------
# On success:
#   Conversion complete: <name>.m4a with embedded lyrics.
#
# =============================================================================

