#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# Download and prepare a small text corpus for pretraining.
#
# This script downloads the TinyStories dataset (~500 MB),
# a high-quality synthetic corpus of short children's stories
# generated by GPT-3.5/4. It's ideal for training small LMs.
#
# Usage:
#   bash scripts/download_data.sh
# ──────────────────────────────────────────────────────────────

set -euo pipefail

DATA_DIR="data"
RAW_DIR="${DATA_DIR}/raw"
CORPUS_FILE="${DATA_DIR}/corpus.txt"

mkdir -p "${RAW_DIR}"

echo "╔══════════════════════════════════════════════╗"
echo "║   Downloading TinyStories dataset...         ║"
echo "╚══════════════════════════════════════════════╝"

# TinyStories — a small but high-quality corpus
URL="https://huggingface.co/datasets/roneneldan/TinyStories/resolve/main/TinyStoriesV2-GPT4-train.txt"

if [ -f "${CORPUS_FILE}" ]; then
    echo "Corpus already exists at ${CORPUS_FILE}, skipping download."
    echo "Delete it to re-download."
else
    echo "Downloading from HuggingFace..."

    if command -v wget &> /dev/null; then
        wget -q --show-progress -O "${RAW_DIR}/TinyStories-train.txt" "${URL}"
    elif command -v curl &> /dev/null; then
        curl -L --progress-bar -o "${RAW_DIR}/TinyStories-train.txt" "${URL}"
    else
        echo "ERROR: Neither wget nor curl found. Please install one of them."
        exit 1
    fi

    echo "Processing..."
    # Just copy — the file is already plain text, one story per line
    cp "${RAW_DIR}/TinyStories-train.txt" "${CORPUS_FILE}"

    echo ""
    echo "Done! Corpus saved to: ${CORPUS_FILE}"
    echo "Lines: $(wc -l < "${CORPUS_FILE}")"
    echo "Size:  $(du -h "${CORPUS_FILE}" | cut -f1)"
fi

echo ""
echo "Next steps:"
echo "  1. Train tokenizer:  python scripts/train_tokenizer.py --corpus ${CORPUS_FILE}"
echo "  2. Run experiment:   python scripts/run_experiment.py --config configs/base.yaml"
