#!/bin/bash
# Generated by ChatGPT. Pretty much just turns the output of ls -l into JSON. 

# Check if a folder was provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 folder"
    exit 1
fi

# Get the folder from the arguments
folder=$1

# Execute the command and store the result in a variable
result=$(ls -l "$folder" | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf("%0o %s\n",k,$9)}' | jq -R -s 'split("\n")[:-1] | map(split(" ")) | map({"name": .[1], "permissions": .[0]})')


# Print the result
echo "$result"
