#!/bin/bash
#Generated by GPT-4o
echo "Updating system..."
sudo yum update -y
sudo yum upgrade -y

if ! command -v docker &> /dev/null; then
  echo "Docker is not installed. Please install Docker and retry."
  exit 1
fi

echo "Docker CLI was found"
echo "Installing snapd..."
sudo yum install epel-release -y
sudo yum install snapd -y
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap

echo "Installing microk8s..."
sudo snap install microk8s --classic --channel=1.30

echo "Joining microk8s group..."
sudo usermod -a -G microk8s $USER
mkdir -p ~/.kube
chmod 0700 ~/.kube

echo "Awaiting microk8s to get ready..."
microk8s status --wait-ready

echo "Setting up add-ons..."
microk8s enable dns
microk8s enable ingress

echo "Setting alias for microk8s kubectl..."
echo "alias kubectl='microk8s kubectl'" >> ~/.bashrc
source ~/.bashrc

echo "Microk8s installation complete!"
while true; do
    read -p "Do you want to start microk8s? (y/n) " yn
    case $yn in
        [Yy]* ) microk8s start; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done