#!/bin/bash
#Generated by GPT-4o

echo "Deleting old Docker versions if exists..."
sudo yum remove -y docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine

echo "Updating system..."
sudo yum update -y

echo "Installing dependencies..."
sudo yum install -y yum-utils \
                    device-mapper-persistent-data \
                    lvm2

echo "Adding Docker's official repository..."
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

echo "Installing Docker..."
sudo yum install -y docker-ce docker-ce-cli containerd.io

echo "Starting and enabling Docker service..."
sudo systemctl start docker
sudo systemctl enable docker

echo "Checking Docker version..."
docker --version

echo "Docker installation complete!"
