#!/bin/bash
# setup-client.sh - turn a Linux/macOS machine into a control terminal for the
# K12 Claude instances (and any other machine running claude-mgr).
#
# This does NOT install claude-mgr or instances locally. It just wires up SSH
# so `ssh claude-k12-<instance>` (and friends) work from this machine.
#
# Idempotent - safe to re-run any time. Nothing is overwritten without asking.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/Clinteastman/claudefarm/main/client/setup-client.sh | bash
#   # or, after cloning:
#   bash desktop/setup-client.sh

set -u

# ---------- Catppuccin Mocha colours ---------------------------------------
M=$'\033[38;2;203;166;247m'   # mauve
G=$'\033[38;2;166;227;161m'   # green
Y=$'\033[38;2;249;226;175m'   # yellow
R=$'\033[38;2;243;139;168m'   # red
S=$'\033[38;2;108;112;134m'   # overlay
C=$'\033[38;2;116;199;236m'   # sapphire
B=$'\033[1m'
N=$'\033[0m'

step()  { printf "\n${M}${B}==>${N} ${B}%s${N}\n" "$*"; }
info()  { printf "    ${S}%s${N}\n" "$*"; }
ok()    { printf "    ${G}OK${N}  ${S}%s${N}\n" "$*"; }
skip()  { printf "    ${S}--${N}  ${S}%s${N}\n" "$*"; }
warn()  { printf "    ${Y}!!${N}  ${Y}%s${N}\n" "$*"; }
fail()  { printf "    ${R}xx${N}  ${R}%s${N}\n" "$*"; exit 1; }
prompt(){ printf "    ${C}${B}?${N}  %s " "$*"; }

# ---------- preflight -------------------------------------------------------

step "preflight"
case "$(uname -s)" in
  Linux*|Darwin*) ok "running on $(uname -s)" ;;
  *) fail "this script targets Linux or macOS - on Windows clone the repo manually and add the Include line to %USERPROFILE%\\.ssh\\config" ;;
esac

for tool in git ssh ssh-keygen; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool not found - install git + openssh first"
done
ok "git, ssh, ssh-keygen present"

# ---------- repo location ---------------------------------------------------

step "homelab repo location"

DEFAULT_REPO="$HOME/github/k12-homelab"
prompt "Clone (or use) the homelab repo at [${DEFAULT_REPO}]:"
read -r REPO_PATH < /dev/tty
REPO_PATH="${REPO_PATH:-$DEFAULT_REPO}"

# Expand ~ in case the user typed it
REPO_PATH="${REPO_PATH/#\~/$HOME}"

if [ -d "$REPO_PATH/.git" ]; then
  info "existing clone found, pulling latest"
  git -C "$REPO_PATH" pull --ff-only --quiet 2>&1 | sed 's/^/        /'
  ok "$REPO_PATH up to date"
else
  info "cloning to $REPO_PATH"
  mkdir -p "$(dirname "$REPO_PATH")"
  git clone --quiet https://github.com/Clinteastman/claudefarm.git "$REPO_PATH"
  ok "cloned"
fi

ALIAS_GLOB="$REPO_PATH/desktop/claude-instances-*.cfg"

# ---------- ssh key --------------------------------------------------------

step "ssh key"
SSH_DIR="$HOME/.ssh"
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

# Find any existing pubkey
PUBKEY=""
for cand in "$SSH_DIR"/id_ed25519.pub "$SSH_DIR"/id_rsa.pub "$SSH_DIR"/id_ecdsa.pub; do
  if [ -f "$cand" ]; then
    PUBKEY="$cand"
    break
  fi
done

if [ -z "$PUBKEY" ]; then
  warn "no SSH key found in $SSH_DIR"
  prompt "Generate one now (ed25519, no passphrase)? [Y/n]:"
  read -r ans < /dev/tty
  if [[ ! "$ans" =~ ^[nN] ]]; then
    ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N "" -C "$(whoami)@$(hostname)" >/dev/null
    PUBKEY="$SSH_DIR/id_ed25519.pub"
    ok "generated $PUBKEY"
  else
    fail "no key, no SSH access - re-run when you've generated one"
  fi
else
  ok "found $PUBKEY"
fi

# ---------- ssh config Include ---------------------------------------------

step "~/.ssh/config Include"
SSHCFG="$SSH_DIR/config"
INCLUDE_LINE="Include $ALIAS_GLOB"
INCLUDE_HEADER="# Claude instance attach + restart aliases - auto-generated by claude-mgr.
# This Include line MUST be at the top of the file, before any Host blocks."

if [ -f "$SSHCFG" ] && grep -qF "$INCLUDE_LINE" "$SSHCFG"; then
  skip "Include line already present"
elif [ -f "$SSHCFG" ] && grep -qE "^\s*Include\s.*claude-instances" "$SSHCFG"; then
  warn "an old/different claude-instances Include is already in $SSHCFG"
  info "edit it to:  $INCLUDE_LINE"
else
  if [ -f "$SSHCFG" ]; then
    cp "$SSHCFG" "$SSHCFG.pre-claude-mgr-$(date +%s).bak"
    info "backed up $SSHCFG"
    # Prepend the Include + header (Include must be at the top)
    tmp="$(mktemp)"
    printf "%s\n%s\n\n" "$INCLUDE_HEADER" "$INCLUDE_LINE" > "$tmp"
    cat "$SSHCFG" >> "$tmp"
    mv "$tmp" "$SSHCFG"
  else
    printf "%s\n%s\n" "$INCLUDE_HEADER" "$INCLUDE_LINE" > "$SSHCFG"
  fi
  chmod 600 "$SSHCFG"
  ok "added Include line to top of $SSHCFG"
fi

# ---------- pubkey to K12 ---------------------------------------------------

step "authorise this machine on K12 LXC 105"
K12_HOST="${K12_HOST:-192.168.50.62}"
K12_USER="${K12_USER:-root}"

printf "    ${S}Your public key (paste this onto K12 if needed):${N}\n\n"
printf "    ${C}"
cat "$PUBKEY" | sed 's/^/    /'
printf "${N}\n"

prompt "Try ssh-copy-id to ${K12_USER}@${K12_HOST} now? [Y/n]:"
read -r ans < /dev/tty
if [[ ! "$ans" =~ ^[nN] ]]; then
  if command -v ssh-copy-id >/dev/null 2>&1; then
    if ssh-copy-id -i "$PUBKEY" "${K12_USER}@${K12_HOST}" 2>&1 | sed 's/^/        /'; then
      ok "pubkey installed on K12"
    else
      warn "ssh-copy-id failed - paste the key above into /root/.ssh/authorized_keys on K12 manually"
    fi
  else
    warn "ssh-copy-id not installed; paste the key above into /root/.ssh/authorized_keys on K12"
  fi
fi

# ---------- test connection -------------------------------------------------

step "test connection"
prompt "Try ssh ${K12_USER}@${K12_HOST} 'hostname' now? [Y/n]:"
read -r ans < /dev/tty
if [[ ! "$ans" =~ ^[nN] ]]; then
  if ssh -o BatchMode=yes -o ConnectTimeout=5 "${K12_USER}@${K12_HOST}" hostname 2>&1; then
    ok "ssh works"
  else
    warn "ssh failed - check key install + LAN reachability"
  fi
fi

# ---------- shell alias for claude-mgr --------------------------------------
#
# claude-mgr lives on the server; this shell alias lets you type
# `claude-mgr` locally and have it ssh through to the running instance
# picker. Idempotent - re-running the script won't duplicate the line.

step "claude-mgr shell alias"
ALIAS_LINE="alias claude-mgr='ssh -t ${K12_USER}@${K12_HOST} claude-mgr'"
ALIAS_MARKER="# claudefarm: claude-mgr picker alias"

# Pick the rc file: zsh if it's the login shell, otherwise bash. macOS
# defaults to zsh; most Linux to bash.
case "$SHELL" in
  */zsh)  RC="$HOME/.zshrc"  ;;
  */bash) RC="$HOME/.bashrc" ;;
  *)      RC="$HOME/.profile" ;;
esac

if [ -f "$RC" ] && grep -qF "$ALIAS_MARKER" "$RC"; then
  skip "alias already in $RC"
else
  prompt "Add 'claude-mgr' shell alias to $RC? [Y/n]:"
  read -r ans < /dev/tty
  if [[ ! "$ans" =~ ^[nN] ]]; then
    touch "$RC"
    {
      printf "\n%s\n" "$ALIAS_MARKER"
      printf "%s\n" "$ALIAS_LINE"
    } >> "$RC"
    ok "appended to $RC - open a new shell (or 'source $RC') to use it"
  else
    skip "alias not added (add manually: $ALIAS_LINE)"
  fi
fi

# ---------- done -----------------------------------------------------------

step "done"
cat <<EOF

  ${G}${B}This client is ready.${N}

  Try one of these (auto-generated from K12's running instances):
EOF

# Show currently-known aliases as a hint
if compgen -G "$REPO_PATH/desktop/claude-instances-*.cfg" >/dev/null 2>&1; then
  for f in "$REPO_PATH"/desktop/claude-instances-*.cfg; do
    awk '/^Host claude-/ {printf "    %s ssh%s %s%s\n", "'"${C}"'", "'"${N}"'", $2, ""}' "$f"
  done
fi

cat <<EOF

  ${S}Pull the repo (${REPO_PATH}) any time to refresh aliases when K12
  spins up new instances.${N}

EOF
