#!/bin/sh
# PreToolUse hook: blocks AI attribution patterns in git commits and gh pr create.
# Reads tool input JSON from stdin; exits 2 to block, 0 to allow.

input=$(cat)

cmd=$(python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('tool_input', {}).get('command', ''))
except Exception:
    pass
" 2>/dev/null <<EOF
$input
EOF
)

# Only act on git commit and gh pr create commands.
case "$cmd" in
  *"git commit"*|*"gh pr create"*)
    ;;
  *)
    exit 0
    ;;
esac

# Patterns that indicate AI attribution — check case-insensitively.
cmd_lower=$(printf '%s' "$cmd" | tr '[:upper:]' '[:lower:]')

for pattern in \
  "co-authored-by.*claude" \
  "co-author.*claude" \
  "generated with claude" \
  "generated by claude" \
  "noreply@anthropic.com" \
  "claude code" \
  "claude sonnet" \
  "claude opus" \
  "claude haiku" \
  "🤖 generated" \
  "claude.ai/code" \
; do
  if printf '%s' "$cmd_lower" | grep -q "$pattern"; then
    cat <<'MSG'

BLOCKED: AI attribution found in commit message or PR body.

CozyTalk rule (CLAUDE.md): Write commits and PRs as a developer would.
No Co-Authored-By tags, no "Generated with Claude" footers, no AI signatures.

Remove the attribution and rewrite the message naturally. Example:

  git commit -m "fix(matchmaking): prevent slot overfill during concurrent joins"

MSG
    exit 2
  fi
done

exit 0
