#!/bin/bash
set -e

# Generated by Claude Skills Manager
# Agent: HackerNewsLetter creator
# Execution ID: db379c7d-b02b-40d0-bb02-c3d2fdd93b08
# Execution Date: 2026-01-24 21:05:22 UTC

# Change to script directory (agent root)
cd "$(dirname "$0")"

# Ensure results directory exists
mkdir -p results

# Read prompt from file (in agent root)
PROMPT_FILE="prompt.txt"

echo "Starting agent execution..."
echo "Results will be written to: results/RESULTS-db379c7d.md"
echo "You can run 'claude --resume' in this directory to interact with the session"
echo ""

# Run Claude with --print for fully automated execution
# --print skips the bypass permissions warning and outputs to stdout
# --chrome enables Claude in Chrome integration for browser automation
claude --print --dangerously-skip-permissions --chrome "$(cat $PROMPT_FILE)"
EXIT_CODE=$?

echo ""
echo "Claude exited with code: $EXIT_CODE"

# Check for results file in results directory
if [ -f "results/RESULTS-db379c7d.md" ]; then
    echo "Results file created: results/RESULTS-db379c7d.md"
    exit 0
else
    echo "Warning: Results file not found"
    exit $EXIT_CODE
fi