#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
PLUGIN_CRATE=helios-plugin-ai-classifier
PLUGIN_WASM=helios_plugin_ai_classifier.wasm
source ../_shared/plugin-demo.sh

export PGPASSWORD=postgres

echo
echo "=== ai-classifier demo ==="

run() {
  local app="$1"; local sql="$2"
  echo
  echo "→ application_name=$app"
  echo "  query: $sql"
  PGAPPNAME="$app" psql -h localhost -p 6432 -U postgres -d demo \
    --no-password -c "$sql" >/dev/null 2>&1 || true
  # The classifier writes per-request KV under
  # helios-plugin-ai-classifier:req:<request_id>:*. We can't easily
  # know the request_id; just dump everything classifier-related.
  echo "  classifier KV (latest 3):"
  curl -s "http://localhost:9090/admin/kv/helios-plugin-ai-classifier?limit=3" 2>/dev/null \
    | jq -r '.[] | "    \(.key) = \(.value)"' 2>/dev/null \
    || echo "    (admin KV endpoint requires the build to expose it)"
}

run "psql"                            "SELECT 1"
run "gpt-shopper"                      "SELECT 1"
run "ClaudeAgent-claude-opus-4-7"      "SELECT 1"
run "psql"                             "/* generated by GPT-4 */ SELECT * FROM users LIMIT 1"

echo
echo "Tear down: ./demo.sh down"
