# This is helpfully generated by ChatGPT 5.2 Thinking
collect_lines() {
  local folder="$1"
  local file_a="$2"
  local file_b="$3"
  local n_a="$4"        # number of lines from start of A
  local n_b="$5"        # number of lines from end of B
  local suffix_a="$6"
  local suffix_b="$7"

  if [[ -z "$folder" || -z "$file_a" || -z "$file_b" || -z "$n_a" || -z "$n_b" ]]; then
    echo "Usage: collect_lines <folder> <fileA> <fileB> <nA> <nB> [suffixA] [suffixB]" >&2
    return 2
  fi

  # basic numeric validation
  [[ "$n_a" =~ ^[0-9]+$ ]] || { echo "Error: nA must be a non-negative integer" >&2; return 2; }
  [[ "$n_b" =~ ^[0-9]+$ ]] || { echo "Error: nB must be a non-negative integer" >&2; return 2; }

  local path_a="$folder/$file_a"
  local path_b="$folder/$file_b"

  [[ -f "$path_a" ]] || { echo "Error: file A not found: $path_a" >&2; return 1; }
  [[ -f "$path_b" ]] || { echo "Error: file B not found: $path_b" >&2; return 1; }

  # First nA lines from A + suffixA
  head -n "$n_a" "$path_a" | awk -v s="${suffix_a-}" '{ print $0 s }'

  # Last nB lines from B + suffixB
  tail -n "$n_b" "$path_b" | awk -v s="${suffix_b-}" '{ print $0 s }'
}

# get the folder from the command line
run_folder=$1

# Collect run files
collect_lines $run_folder CustRangeMap--no-sort-16.0-hs4s4.dat CustRangeMap--no-sort-16.0-cpsbbf18.dat 4 2 " (4,4)" " (1,8)" > $run_folder/cpsbbf.dat
wc -l $run_folder/cpsbbf.dat
cat $run_folder/cpsbbf.dat

gnuplot -c paper_plot_speedup_bars.gp $run_folder/
echo "speedup bars are generated"

cache_folder=$2
# Collect cache files
collect_lines $cache_folder CustRangeMap--no-sort-16.0-hs4s4.dat CustRangeMap--no-sort-16.0-cpsbbf18.dat 2 2 " (4,4)" " (1,8)" > $cache_folder/cpsbbf.dat
wc -l $cache_folder/cpsbbf.dat
cat $cache_folder/cpsbbf.dat

gnuplot -c paper_plot_cache.gp $cache_folder/
echo "cache bars are generated"

workload_folder=$3

gnuplot -c paper_plot_workload_time.gp $workload_folder/
echo "workload bars are generated"

gnuplot paper_plot_mem_print_plot_bw.gp
echo "memory plots are generated"
