#!/usr/bin/env bash

# All code below was generated by ChatGPT v4 
set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
set -o xtrace
fi

# cd "$(dirname "$0")"

display_help() {
    echo "Usage: $0 [option...] " >&2
    echo
    echo "   -d,  specify the directory (default is ./lib)"
    echo "   -h,  show this help text"
    echo
    exit 1
}

main() {
    dir="lib"
    while getopts ":d:h" opt; do
        case $opt in
            d) dir="$OPTARG"
            ;;
            h) display_help
            ;;
            \?) echo "Invalid option -$OPTARG" >&2
                display_help
            ;;
            :)  echo "Option -$OPTARG requires an argument." >&2
                display_help
            ;;
        esac
    done

    total=0
    while IFS= read -r -d '' file
    do
        if [ -f "$file" ]; then
            lines=$(wc -l < "$file")
            printf "%-40s %s\n" "$(basename "$file")" "$lines"
            total=$((total + lines))
        fi
    done < <(find "$dir" -type f -print0)
    printf "%-40s %s\n" "Total lines of code:" "$total"
}

main "$@"
