#!/usr/bin/env sh

## Prerequesites
get_script_dir() {
	# Get the directory of the currently running script
	local script_dir=$(dirname "$(realpath "$0")")
	echo "$script_dir"
}
SCRIPT_DIR=$(get_script_dir)
ROOT_DIR="$SCRIPT_DIR/../.."

## Usage
usage() {
	echo "Usage: $0 --for <app-name> --on <bridge-name[.vlan-id]>"
	echo "Eg: $0 --for firewall-gw --on vmbr1"
	echo "Eg: $0 --for reverse-proxy --on vmbr3.30"
	echo "Eg: $0 --for media-server --on vmbr3.31"
 	exit 1
}

## Input verification
APP=""
ON=""
while [ $# -gt 0 ]; do
	case "$1" in
		--for) 
			APP="$2"
			shift 2
			;;
		--on)  
			ON="$2" 
			shift 2
			;;
		--help) 
			usage
			;;
		*) 
			usage
			;;
	esac
done

[ -n "${APP:-}" ] || usage
[ -n "${ON:-}" ]  || usage

BRIDGE="${ON%%.*}"
if [ "$ON" != "$BRIDGE" ]; then
  VLAN="${ON#*.}"
else
  VLAN=""
fi

#
## Core
#
FILE="$ROOT_DIR/apps/$APP/infra/proxmox.yml"

# == Generated by Chatgpt ==
# Parse the YAML in awk (handles the given structure and common variations)
awk -v BRIDGE="$BRIDGE" -v VLAN="$VLAN" '
function ltrim(s){ sub(/^[ \t]+/, "", s); return s }
function rtrim(s){ sub(/[ \t]+$/, "", s); return s }
function trim(s){ return rtrim(ltrim(s)) }
function firsttok(s){ s=trim(s); split(s,a,/[ \t]+/); return a[1] }

BEGIN{
	inNics=0; inTrunks=0;
	curBridge=""; curVlan="";
	matchThis=0; found=0; foundBridge=0; matchedNicTrunked=0;
}

{
	line=$0
	sub(/#.*/,"", line)            # strip comments
	line=trim(line)
	if (line=="") next

	# Enter nics section
	if (!inNics) {
		if (line ~ /^nics[ \t]*:/) { inNics=1; next }
		else next
	}

	# New NIC bridge entry (e.g., "- bridge: vmbr2" or "bridge: vmbr2")
	if (line ~ /^-?[ \t]*bridge[ \t]*:/) {
		val=line; sub(/^-?[ \t]*bridge[ \t]*:[ \t]*/, "", val)
		curBridge=firsttok(val)
		matchThis = (curBridge==BRIDGE)
		if (matchThis) { foundBridge=1 }
		# reset per-NIC context
		inTrunks=0; matchedNicTrunked=0; curVlan=""
		next
	}

	# Trunks section under the current NIC
	if (line ~ /^trunks[ \t]*:/) {
		if (matchThis) { inTrunks=1; matchedNicTrunked=1 }
		next
	}

	# Inside trunk list: capture id
	if (inTrunks && line ~ /^-?[ \t]*id[ \t]*:/) {
		v=line; sub(/^-?[ \t]*id[ \t]*:[ \t]*/, "", v)
		curVlan=firsttok(v)
		next
	}

	# IPv4 entries
	if (line ~ /^ipv4[ \t]*:/) {
		ip=line; sub(/^ipv4[ \t]*:[ \t]*/, "", ip)
		ip=firsttok(ip)

		if (matchThis) {
			# Remove CIDR notation (e.g., /24) from IP address
			sub(/\/[0-9]+$/, "", ip)
			
			# trunked case with requested VLAN
			if (inTrunks && VLAN != "" && curVlan != "" && curVlan == VLAN) {
				print ip; found=1; exit 0
			}
			# non-trunked case without VLAN requested
			if (!inTrunks && VLAN == "") {
				print ip; found=1; exit 0
			}
		}
		next
	}

	# If we hit a new list item at NIC level, clear trunk-local state
	if (line ~ /^-[ \t]*/) {
		if (! (line ~ /^-?[ \t]*id[ \t]*:/)) {
			# likely a new NIC item; reset trunk context unless still under same NIC
			if (! (line ~ /^-?[ \t]*bridge[ \t]*:/)) {
				inTrunks = inTrunks # unchanged
			}
		}
	}
}

END{
	if (found) exit 0
	if (!foundBridge) {
		printf("Error: bridge \"%s\" not found in nics.\n", BRIDGE) > "/dev/stderr"; exit 1
	}
	if (VLAN == "" && matchedNicTrunked == 1) {
		printf("Error: bridge \"%s\" is trunked; specify a VLAN: --on %s.<vlan-id>\n", BRIDGE, BRIDGE) > "/dev/stderr"; exit 1
	}
	if (VLAN != "" && matchedNicTrunked == 0) {
		printf("Error: VLAN %s requested but bridge \"%s\" is not trunked.\n", VLAN, BRIDGE) > "/dev/stderr"; exit 1
	}
	if (VLAN != "" && matchedNicTrunked == 1) {
		printf("Error: VLAN %s not found on bridge \"%s\".\n", VLAN, BRIDGE) > "/dev/stderr"; exit 1
	}
	printf("Error: no ipv4 found for bridge \"%s\"%s.\n", BRIDGE, (VLAN==""?"":sprintf(" (vlan %s)", VLAN))) > "/dev/stderr"; exit 1
}
' "$FILE"
