#!/bin/bash
################################################################################
# AIFX v2 - Check Services Status Script
#
# This script checks the status of all AIFX v2 services
#
# Usage:
#   ./check-services.sh
#
# Generated by Claude Code
################################################################################

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

check_service() {
    local name=$1
    local url=$2
    local session=$3

    printf "%-20s" "$name:"

    # Check tmux session
    if tmux has-session -t $session 2>/dev/null; then
        printf "${GREEN}✓${NC} Running (tmux)  "
    else
        printf "${RED}✗${NC} Not Running     "
        echo ""
        return
    fi

    # Check HTTP endpoint
    if curl -s $url > /dev/null 2>&1; then
        printf "${GREEN}✓${NC} Responding"
    else
        printf "${YELLOW}⚠${NC} Not Responding"
    fi

    echo ""
}

check_db_service() {
    local name=$1
    local check_cmd=$2

    printf "%-20s" "$name:"

    if eval $check_cmd > /dev/null 2>&1; then
        printf "${GREEN}✓${NC} Running"
    else
        printf "${RED}✗${NC} Not Running"
    fi

    echo ""
}

echo "=============================================================================="
echo "              AIFX v2 - Service Status Check                                "
echo "=============================================================================="
echo ""
echo "Application Services:"
echo "-------------------"
check_service "Backend" "http://localhost:3000/api/v1/health" "aifx-backend"
check_service "Frontend" "http://localhost:5173" "aifx-frontend"
check_service "ML Engine" "http://localhost:8000/health" "aifx-ml"

echo ""
echo "Infrastructure Services:"
echo "-------------------"
check_db_service "PostgreSQL" "sudo systemctl is-active --quiet postgresql"
check_db_service "Redis" "sudo systemctl is-active --quiet redis-server"

echo ""
echo "Listening Ports:"
echo "-------------------"
netstat -tlnp 2>&1 | grep -E ':(3000|5173|8000|5432|6379)' | awk '{print $4, $7}' || echo "No services listening"

echo ""
echo "Tmux Sessions:"
echo "-------------------"
tmux list-sessions 2>/dev/null || echo "No tmux sessions running"

echo ""
echo "=============================================================================="
echo ""
