#!/usr/bin/env bash

# Script to detect delay/Thread.sleep usage in test files with Compose rules
# Tests using Compose rules should use waitUntil() instead of delays for reliability

# Generated by Claude Code

set -e

TEST_DIR="app/src/androidTest"
ERRORS=0

# Files to exclude from checks (temporary allowance)
EXCLUDED_FILES=(
  "$TEST_DIR/java/com/github/meeplemeet/ui/MapScreenTest.kt"
  "$TEST_DIR/java/com/github/meeplemeet/end2end/E2E_M1.kt"
  "$TEST_DIR/java/com/github/meeplemeet/end2end/E2E_M2.kt"
  "$TEST_DIR/java/com/github/meeplemeet/end2end/E2E_M3.kt"
  "$TEST_DIR/java/com/github/meeplemeet/utils/AuthUtils.kt"
)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "🔍 Checking for delay/Thread.sleep in Compose test files..."
echo ""

# Check if test directory exists
if [ ! -d "$TEST_DIR" ]; then
  echo -e "${RED}Error: Test directory not found: $TEST_DIR${NC}"
  exit 1
fi

# Find all Kotlin test files
while IFS= read -r file; do
  # Skip explicitly excluded files
  skip_file=false
  for excluded in "${EXCLUDED_FILES[@]}"; do
    if [ "$file" = "$excluded" ]; then
      skip_file=true
      break
    fi
  done

  if [ "$skip_file" = true ]; then
    continue
  fi

  # Check if file creates a Compose rule
  # Look for: createComposeRule, createAndroidComposeRule, or ComposeContentTestRule
  has_compose_rule=$(grep -E '(createComposeRule|createAndroidComposeRule|ComposeContentTestRule)' "$file" 2>/dev/null || true)

  if [ -z "$has_compose_rule" ]; then
    # Skip files without Compose rules
    continue
  fi

  # Check for delay() or Thread.sleep() calls
  # Pattern matches: delay(...), Thread.sleep(...), runBlocking with delay
  delay_matches=$(grep -nE '(delay\s*\(|Thread\.sleep\s*\()' "$file" 2>/dev/null || true)

  if [ -n "$delay_matches" ]; then
    if [ $ERRORS -eq 0 ]; then
      echo -e "${BLUE}Files with Compose rules using delay/Thread.sleep:${NC}"
      echo ""
    fi

    echo -e "${RED}✗ Delay found in: ${file#*/}${NC}"
    echo "$delay_matches" | while IFS= read -r line; do
      line_num=$(echo "$line" | cut -d: -f1)
      line_content=$(echo "$line" | cut -d: -f2-)
      echo -e "  ${YELLOW}Line $line_num: $line_content${NC}"
    done
    echo ""
    ERRORS=$((ERRORS + 1))
  fi
done < <(find "$TEST_DIR" -name "*.kt" -type f)

# Summary
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [ $ERRORS -eq 0 ]; then
  echo -e "${GREEN}✓ No delays detected in Compose test files!${NC}"
  exit 0
else
  echo -e "${RED}✗ Found delays in $ERRORS file(s) with Compose rules${NC}"
  echo ""
  echo "Compose tests should use waitUntil() instead of delay/Thread.sleep."
  echo "Delays make tests flaky and slow. waitUntil() is deterministic."
  echo ""
  echo "Example:"
  echo "  ❌ delay(1000)"
  echo "  ❌ Thread.sleep(1000)"
  echo "  ✅ composeTestRule.waitUntil(timeoutMillis = 5000) {"
  echo "       // condition to wait for"
  echo "     }"
  exit 1
fi