#!/bin/bash

# Color codes for shell scripts
# NOTE: These variables were generated by ChatGPT.

# Text colors
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'

# Text styles
BOLD='\e[1m'
RESET='\e[0m'  # Reset all styles


# Functions for writing test messages
test_success() {
    local TEST_FILE="$1"
    local TEST_NAME="$2"
    local MSG="$3"

    echo -e "${TEST_FILE} - ${YELLOW}${BOLD}${TEST_NAME}${RESET} ${GREEN}${BOLD}SUCCESS:${RESET} ${MSG}"
}

test_failure() {
    local TEST_FILE="$1"
    local TEST_NAME="$2"
    local MSG="$3"

    echo -e "${TEST_FILE} - ${YELLOW}${BOLD}${TEST_NAME}${RESET} ${RED}${BOLD}FAILURE:${RESET} ${MSG}"
}