#!/bin/bash
# IKEMEN Forge — Scaffold a new stage directory
# Usage: scaffold-stage.sh <stage-name> [base-path]

STAGE_NAME="${1:-arena}"
BASE_PATH="${2:-.}"
STAGE_DIR="$BASE_PATH/stages/$STAGE_NAME"

echo "=== IKEMEN Forge: Scaffolding Stage ==="
echo "Stage: $STAGE_NAME"
echo "Location: $STAGE_DIR"
echo ""

# Create stage directory
mkdir -p "$STAGE_DIR"
mkdir -p "$STAGE_DIR/sprites"

echo "Created directories:"
echo "  stages/$STAGE_NAME/"
echo "  stages/$STAGE_NAME/sprites/  (for raw background layer PNGs)"
echo ""

# List expected files
echo "Expected files (to be generated by Claude):"
echo "  $STAGE_NAME.def  — Stage definition"
echo "  $STAGE_NAME.sff  — Stage sprites (compiled)"
echo ""

echo "=== Stage scaffold ready! ==="
