#!/bin/bash
# This script was generated by ChatGPT
# Script to create directories and files for the first 25 days of the month

# Loop through days 1 to 25
for day in $(seq -w 2 25); do
  # Create the main directory for the day
  day_dir="day_$day"
  mkdir -p "$day_dir"

  # Create the input text file with .txt extension
  touch "$day_dir/input.txt"

  # Create subdirectories and Julia source files
  for part in 1 2; do
    part_dir="$day_dir/part_$part"
    mkdir -p "$part_dir"

    # Generate Julia source file name with two-digit day
    julia_file="$part_dir/d${day}p$part.jl"

    # Write initial content to the Julia file
    cat <<EOF > "$julia_file"
# Day $day, Part $part
#=
Plan of Attack:
1. Step one description.
2. Step two description.
3. Additional steps...
=#
EOF
  done
done

echo "Directories and files created successfully!"
