#!/bin/bash

# TOMTOM command line script
# Usage: bash run_tomtom.sh

# Set variables
MOTIF_FILE="meme_output/meme.txt"
FASTA="target_sequences.fa"
# Motif ID from MEME results to search for (if we only want to search for one motif)
ID="AWTATTTWWWTRWAW"

fimo --motif "$ID" \
     --oc fimo_output \
     "$MOTIF_FILE" \
     "$FASTA"

# Get the number of sequences with at least one motif occurrence. ***Generated by Claude Sonnet 4.5***
# Skip the header line
# Count unique sequence names in the 3rd column
# Print the count with a label
awk 'NR > 1 \
    {sequences[$3]++} \
    END {print "Unique sequences:", length(sequences)}' fimo_output/fimo.tsv