#!/usr/bin/env bash
# optimize-repo.sh — staged disk cleanup for the DevSkyy repo
#
# Generated by Claude after a forensic audit on 2026-04-24.
# Default behavior is DRY-RUN. Pass --execute to actually delete.
#
# Safety contract:
#   - Never touches .git
#   - Never touches .env or any secret-bearing file
#   - Never touches user source code
#   - Each tier is opt-in; no tier runs unless requested
#   - Dry-run by default; --execute is required for actual deletion
#
# Tiers (run order: safest first):
#   tier1 — caches (.mypy_cache, .ruff_cache, .pytest_cache, coverage/, dist/, .next/, htmlcov/)
#   tier2 — empty AI-tool ghost directories at repo root (.augment, .factory, etc.)
#   tier3 — elite-layer-{2..6} workspace snapshots in $HOME (NOT in this repo)
#   tier4 — node_modules + .venv (regeneratable; will need npm install + uv sync after)
#
# Usage:
#   ./scripts/optimize-repo.sh                  # dry-run all tiers
#   ./scripts/optimize-repo.sh tier1            # dry-run tier 1 only
#   ./scripts/optimize-repo.sh tier1 --execute  # actually run tier 1
#   ./scripts/optimize-repo.sh all --execute    # run all tiers (with prompts between)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

EXECUTE=false
TIER="all"
for arg in "$@"; do
  case "$arg" in
    --execute) EXECUTE=true ;;
    tier1|tier2|tier3|tier4|all) TIER="$arg" ;;
    -h|--help)
      sed -n '2,30p' "${BASH_SOURCE[0]}"
      exit 0 ;;
  esac
done

ACTION="DRY-RUN"
$EXECUTE && ACTION="EXECUTE"

bytes_h() { du -sh "$1" 2>/dev/null | awk '{print $1}'; }
log()    { printf "  %s\n" "$*"; }
section(){ printf "\n=== %s [%s] ===\n" "$1" "$ACTION"; }

confirm() {
  $EXECUTE || return 0
  printf "\nProceed with %s? [y/N] " "$1"
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

run_tier1() {
  section "TIER 1 — caches (regenerated by next build/test)"
  local total=0
  for path in .mypy_cache .ruff_cache .pytest_cache coverage htmlcov dist build .next \
              **/.mypy_cache **/.ruff_cache **/.pytest_cache; do
    for d in $path; do
      [ -e "$d" ] || continue
      [[ "$d" == *node_modules* ]] && continue
      [[ "$d" == *.venv* ]] && continue
      size=$(bytes_h "$d")
      log "$ACTION $size  $d"
      if $EXECUTE; then
        rm -rf "$d"
      fi
    done
  done
  log "(tier 1 complete)"
}

run_tier2() {
  section "TIER 2 — empty AI-tool ghost directories at repo root"
  for d in .adal .augment .bob .codebuddy .commandcode .continue .cortex .crush .factory; do
    if [ -d "$d" ]; then
      file_count=$(find "$d" -type f 2>/dev/null | wc -l | tr -d ' ')
      if [ "$file_count" = "0" ]; then
        log "$ACTION (empty)  $d"
        $EXECUTE && rmdir "$d" 2>/dev/null || true
      else
        log "SKIP (has $file_count files)  $d"
      fi
    fi
  done
  log "(tier 2 complete)"
}

run_tier3() {
  section "TIER 3 — elite-layer-{2..6} workspace snapshots (~3.7GB outside this repo)"
  log "Note: these live in \$HOME, not in this repo. elite-integrated is preserved as the canonical workspace."
  if ! confirm "delete elite-layer-2 through elite-layer-6"; then
    log "skipped (no confirmation)"
    return
  fi
  for n in 2 3 4 5 6; do
    target="$HOME/elite-layer-$n"
    if [ -d "$target" ]; then
      size=$(bytes_h "$target")
      log "$ACTION $size  $target"
      if $EXECUTE; then
        rm -rf "$target"
      fi
    fi
  done
  log "(tier 3 complete)"
}

run_tier4() {
  section "TIER 4 — node_modules + .venv (~7.9GB, will need rebuild)"
  log "After this runs: npm install (or pnpm install), then 'uv sync' to restore the venv."
  if ! confirm "delete node_modules and .venv"; then
    log "skipped (no confirmation)"
    return
  fi
  for d in node_modules .venv; do
    [ -d "$d" ] || continue
    size=$(bytes_h "$d")
    log "$ACTION $size  $d"
    if $EXECUTE; then
      rm -rf "$d"
    fi
  done
  log "(tier 4 complete)"
}

case "$TIER" in
  tier1) run_tier1 ;;
  tier2) run_tier2 ;;
  tier3) run_tier3 ;;
  tier4) run_tier4 ;;
  all)
    run_tier1
    run_tier2
    run_tier3
    run_tier4
    ;;
esac

printf "\n=== summary ===\n"
$EXECUTE && echo "Disk reclamation done. Recommend running 'git status' to confirm no source files were affected." \
         || echo "Dry-run only. Re-run with --execute to actually delete."
