#!/usr/bin/env bash

# ============================================================
# Claude Guardrails Scaffold Script
# Creates directory structure and stub files for code constraints
# ============================================================

set -e

BASE_DIR="claude_rules"

echo "Creating Claude guardrails structure..."

# Create main directory
mkdir -p $BASE_DIR/code_templates

# ----------------------------
# README.md
# ----------------------------
cat << 'EOF' > $BASE_DIR/README.md
# Claude Code Guardrails

This directory defines the rules, constraints, and architectural guardrails
for LLM-generated code in this repository.

Claude is treated as an untrusted code generator.

All generated code must comply with:
- invariants.md
- anti_patterns.md
- architecture.md
- prompt_contract.md

Violations must result in rejection and correction.

This system exists to prevent:
- silent failures
- spaghetti code
- hidden state bugs
- non-deterministic behavior
EOF

# ----------------------------
# invariants.md
# ----------------------------
cat << 'EOF' > $BASE_DIR/invariants.md
# Invariants (DO NOT VIOLATE)

1. No silent failure
   - No bare except
   - No pass in exception blocks

2. Deterministic behavior
   - All randomness must be seeded
   - No hidden stochasticity

3. No implicit state mutation
   - Functions must be pure unless explicitly marked

4. Explicit I/O
   - All external reads/writes must be logged

5. Type safety
   - All interfaces must be typed
   - No implicit casting

6. Validation required
   - All outputs must be validated against schema or assertions
EOF

# ----------------------------
# anti_patterns.md
# ----------------------------
cat << 'EOF' > $BASE_DIR/anti_patterns.md
# Forbidden Patterns

The following are strictly disallowed:

- try/except: pass
- bare except
- mutable default arguments
- hidden global state
- functions longer than 50 lines
- deeply nested logic (>3 levels)
- implicit type conversion
- magic numbers without explanation
- side effects in utility functions
EOF

# ----------------------------
# architecture.md
# ----------------------------
cat << 'EOF' > $BASE_DIR/architecture.md
# Architecture Rules

This document defines allowed system structure.

## Principles
- Clear module boundaries
- Explicit data flow
- No hidden dependencies

## State Management
- All state must be explicit
- No implicit mutation across modules

## LangGraph / Agent Systems
- State must be minimal and well-defined
- Each node must have clear input/output contracts

## Code Organization
- Small, composable functions
- No cross-module side effects
EOF

# ----------------------------
# tests_required.md
# ----------------------------
cat << 'EOF' > $BASE_DIR/tests_required.md
# Testing Requirements

All code generated by Claude must include:

1. Unit tests
   - Cover core logic
   - Include edge cases

2. Invariant checks
   - Assertions must be present

3. Determinism tests
   - Outputs must be reproducible

4. Failure tests
   - Explicitly test invalid inputs

Code without tests is considered invalid.
EOF

# ----------------------------
# prompt_contract.md
# ----------------------------
cat << 'EOF' > $BASE_DIR/prompt_contract.md
# Claude Prompt Contract

You MUST follow all rules in claude_rules/.

If a request violates any invariant:
- STOP
- Explain the violation
- Propose a safe alternative

You MUST NOT:
- introduce silent failures
- modify unrelated files
- create hidden state
- bypass validation

All outputs must:
- be deterministic
- be testable
- include validation
EOF

# ----------------------------
# code_templates/example.py
# ----------------------------
cat << 'EOF' > $BASE_DIR/code_templates/example.py
"""
Example template for Claude-generated code.
"""

from typing import List


def example_function(x: float) -> float:
    """
    Example function with invariant enforcement.
    """

    assert isinstance(x, (int, float)), "Input must be numeric"

    result = x * 2

    assert result >= 0, "Result must be non-negative"

    return result
EOF

# ----------------------------
# Optional: tools directory for invariant checker
# ----------------------------
mkdir -p tools

cat << 'EOF' > tools/invariant_checker.py
"""
Basic invariant checker stub.
"""

def check_no_silent_failures(code: str):
    if "except:" in code:
        raise AssertionError("Bare except detected")

    if "pass" in code:
        raise AssertionError("Pass statement detected")


def run_all_checks(code: str):
    check_no_silent_failures(code)
EOF

echo "✅ Claude guardrails scaffold created successfully."