#!/usr/bin/env bash
# 06b-mine-ci-workflows-v2.sh
#
# Re-mines Dataset B (CI) with REAL provenance, replacing the earlier synthetic
# corpus. Records a full manifest (repo, path, ref, commit date) so exact dates
# are recoverable.
#
#   HUMAN cohort: real .github/workflows/*.y[a]ml files from mature repositories,
#                 taken at each repo's last commit strictly BEFORE the pre-ChatGPT
#                 cutoff (2022-11-30). GitHub Actions did not exist meaningfully
#                 before 2020, so the CI human boundary is the ChatGPT launch
#                 rather than the 2020 boundary used for GNU/Git.
#
#   LLM cohort:   real workflow files carrying EXPLICIT AI attribution
#                 (ChatGPT / Copilot / Claude / GPT) found via GitHub code search,
#                 verified by re-checking the attribution phrase in the file body.
#
# Output:
#   corpus/ci/human/   corpus/ci/llm/   corpus/ci/mining-manifest.csv
#   (the previous synthetic corpus is moved to corpus/ci/_synthetic_backup/)
#
# Requires: gh (authenticated), jq.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HUMAN_DIR="$ROOT/corpus/ci/human"
LLM_DIR="$ROOT/corpus/ci/llm"
BACKUP_DIR="$ROOT/corpus/ci/_synthetic_backup"
MANIFEST="$ROOT/corpus/ci/mining-manifest.csv"

HUMAN_TARGET=210
LLM_TARGET=210
HUMAN_CUTOFF="2022-11-30T00:00:00Z"   # ChatGPT public launch boundary
PER_REPO_CAP=12                        # diversity: cap files per human repo

command -v gh >/dev/null || { echo "gh not found"; exit 1; }
command -v jq >/dev/null || { echo "jq not found"; exit 1; }

log() { echo "[$(date +%H:%M:%S)] $*" >&2; }

# Back up the synthetic corpus once, then start clean.
if [[ ! -d "$BACKUP_DIR" ]]; then
  mkdir -p "$BACKUP_DIR"
  [[ -d "$HUMAN_DIR" ]] && cp -r "$HUMAN_DIR" "$BACKUP_DIR/human"
  [[ -d "$LLM_DIR" ]]   && cp -r "$LLM_DIR"   "$BACKUP_DIR/llm"
  log "Backed up synthetic CI corpus to $BACKUP_DIR"
fi
rm -rf "$HUMAN_DIR" "$LLM_DIR"
mkdir -p "$HUMAN_DIR" "$LLM_DIR"

echo "source,repo,path,ref,commit_date,evidence" > "$MANIFEST"

urlenc() { jq -rn --arg s "$1" '$s|@uri'; }

download_raw() {  # repo path ref outfile
  local repo="$1" path="$2" ref="$3" out="$4" url
  url="repos/$repo/contents/$(urlenc "$path")"
  [[ -n "$ref" ]] && url="${url}?ref=$ref"
  local content
  content="$(gh api "$url" --jq '.content' 2>/dev/null)" || return 1
  [[ -z "$content" || "$content" == "null" ]] && return 1
  printf '%s' "$content" | base64 -d > "$out" 2>/dev/null || return 1
  [[ -s "$out" ]] || { rm -f "$out"; return 1; }
  return 0
}

# PART 1: HUMAN — real workflows at last commit before the cutoff
log "PART 1: human CI workflows (last commit before $HUMAN_CUTOFF)"

HUMAN_REPOS=(
  docker/compose moby/moby docker/cli containerd/containerd
  kubernetes/kubernetes helm/helm grafana/grafana prometheus/prometheus
  elastic/elasticsearch hashicorp/terraform hashicorp/vault ansible/ansible
  rails/rails django/django pallets/flask nodejs/node npm/cli
  facebook/react vuejs/vue angular/angular webpack/webpack babel/babel
  eslint/eslint prettier/prettier vercel/next.js gatsbyjs/gatsby
  tensorflow/tensorflow pytorch/pytorch scikit-learn/scikit-learn
  pandas-dev/pandas numpy/numpy redis/redis envoyproxy/envoy
  istio/istio traefik/traefik kong/kong sentry/getsentry
  apache/airflow celery/celery scipy/scipy huggingface/transformers
  microsoft/TypeScript aquasecurity/trivy falcosecurity/falco
)

human_count=0
for repo in "${HUMAN_REPOS[@]}"; do
  (( human_count >= HUMAN_TARGET )) && break
  ref="$(gh api "repos/$repo/commits?until=$HUMAN_CUTOFF&per_page=1" --jq '.[0].sha' 2>/dev/null)"
  [[ -z "$ref" || "$ref" == "null" ]] && { log "  $repo: no pre-cutoff commit"; continue; }
  cdate="$(gh api "repos/$repo/commits/$ref" --jq '.commit.committer.date' 2>/dev/null)"
  mapfile -t wfs < <(gh api "repos/$repo/git/trees/$ref?recursive=1" \
      --jq '.tree[] | select(.path|test("^\\.github/workflows/.*\\.ya?ml$")) | .path' 2>/dev/null)
  log "  $repo: ${#wfs[@]} workflow files at $ref"
  local_n=0
  for wf in "${wfs[@]}"; do
    (( human_count >= HUMAN_TARGET )) && break
    (( local_n >= PER_REPO_CAP )) && break
    [[ -z "$wf" ]] && continue
    safe="${repo//\//_}__${wf//\//_}"
    if download_raw "$repo" "$wf" "$ref" "$HUMAN_DIR/$safe"; then
      human_count=$((human_count+1)); local_n=$((local_n+1))
      echo "human,$repo,$wf,$ref,$cdate,real_pre_chatgpt" >> "$MANIFEST"
    fi
  done
done
log "HUMAN collected: $human_count"

# PART 2: LLM — workflows with explicit AI attribution
log "PART 2: LLM CI workflows (explicit AI attribution)"

LLM_QUERIES=(
  '"generated by Claude" path:.github/workflows'
  '"Generated by Claude Code" path:.github/workflows'
  '"Generated by ChatGPT" path:.github/workflows'
  '"generated with ChatGPT" path:.github/workflows'
  '"generated with GitHub Copilot" path:.github/workflows'
  '"generated by Copilot" path:.github/workflows'
  '"written by ChatGPT" path:.github/workflows'
  '"created by ChatGPT" path:.github/workflows'
  '"generated by GPT-4" path:.github/workflows'
  '"this workflow was generated by" path:.github/workflows'
)
# Phrase that must appear in the downloaded file body to confirm attribution.
ATTR_RE='(generated|created|written|authored).{0,40}(chatgpt|gpt-?4|gpt-?3|copilot|claude|gemini|\bgpt\b|\bllm\b)'

llm_count=0
declare -A seen
for q in "${LLM_QUERIES[@]}"; do
  (( llm_count >= LLM_TARGET )) && break
  for page in 1 2 3 4 5; do
    (( llm_count >= LLM_TARGET )) && break
    results="$(gh api -X GET search/code -f q="$q" -F per_page=100 -F page=$page \
               --jq '.items[] | "\(.repository.full_name)\t\(.path)"' 2>/dev/null)" || break
    [[ -z "$results" ]] && break
    while IFS=$'\t' read -r repo path; do
      [[ -z "$repo" || -z "$path" ]] && continue
      (( llm_count >= LLM_TARGET )) && break
      key="$repo/$path"
      [[ -n "${seen[$key]:-}" ]] && continue
      seen[$key]=1
      safe="${repo//\//_}__${path//\//_}"
      tmp="$LLM_DIR/.tmp_$safe"
      if download_raw "$repo" "$path" "" "$tmp"; then
        if grep -qiE "$ATTR_RE" "$tmp" 2>/dev/null; then
          mv "$tmp" "$LLM_DIR/$safe"
          cdate="$(gh api "repos/$repo/commits?path=$(urlenc "$path")&per_page=1" \
                   --jq '.[0].commit.author.date' 2>/dev/null)"
          llm_count=$((llm_count+1))
          echo "llm,$repo,$path,,$cdate,ai_attributed" >> "$MANIFEST"
        else
          rm -f "$tmp"
        fi
      else
        rm -f "$tmp"
      fi
    done <<< "$results"
    sleep 2   # respect code-search rate limit (30/min)
  done
done
log "LLM collected: $llm_count"

echo >&2
log "DONE. human=$human_count llm=$llm_count"
log "Manifest: $MANIFEST"
